if(title == 'Add-to-cart animation'){var videoSource = 'bjnHoBV8SCk';}
if(title == 'Chat box'){var videoSource = 'WZqVs5D0KzA';}
if(title == 'Cookie box'){var videoSource = 'gpmxPLbauw8';}
if(title == 'Delivery time'){var videoSource = 'rgtWh4RQWTw';}
if(title == 'F.A.Q page'){var videoSource = 'lmhsHB5lHN8';}
if(title == 'Instagram feed'){var videoSource = 'a8_5N6wNnwI';}
if(title == 'Live view'){var videoSource = 'V1TYD-Z6OTg';}
if(title == 'Product tabs'){var videoSource = 'N0vh9pcnkag';}
if(title == 'Sales pop'){var videoSource = 'Ud_YvHUAhYE';}
if(title == 'Trust badge'){var videoSource = 'Wjwv5G9Y8vk';}
if(title == 'Sticky add-to-cart'){var videoSource = 'Y6qmf5hEuSU';}
if(title == 'Product video'){var videoSource = 'h7t1QYObQXc';}
if(title == 'Shop protect'){var videoSource = 'sGZhpPAe2Yc';}
if(title == 'Mega menu'){var videoSource = 'b4OtktdtatU';}
if(title == 'Newsletter pop-up'){var videoSource = 'xRhq0EvBqVg';}
if(title == 'Collection add-to-cart'){var videoSource = 'P8GwQ_rN8XI';}
if(title == 'Upsell pop-up'){var videoSource = 'G_UuhJeRzqs';}
if(title == 'Discount Saved'){var videoSource = 'JproinpFJuU';}
if(title == 'Cart countdown'){var videoSource = '1Eif6LLnnqg';}
if(title == 'Linked options'){var videoSource = 'zfHvGKgHecU';}
if(title == 'Sales countdown'){var videoSource = '6YeuNEQWh8c';}
if(title == 'Inventory quantity'){var videoSource = '0y-TmTS2ryM';}
if(title == 'Color swatches'){var videoSource = 'LH_Xzwx-Vfg';}
if(title == 'Cart discount'){var videoSource = 'RvJe5-uUWEo';}
if(title == 'Quick view'){var videoSource = '3AXJj7UOr60';}
if(title == 'Smart search'){var videoSource = 'fQmYha5aCFo';}
if(title == 'Upsell bundles'){var videoSource = 'PlcT73BM1wk';}
if(title == 'Skip cart'){var videoSource = 'TJhHJEwV9jg';}
if(title == 'Cart goal'){var videoSource = '5UetdWCAUGA';}
if(title == 'Pricing table'){var videoSource = '2SxUeeR4_5M';}
if(title == 'Wish list'){var videoSource = 'NL2zfVoR290';}
if(title == 'Quantity break'){var videoSource = 'VkaRpFJTNEw';}
if(title == 'Age check'){var videoSource = 'NL2zfVoR290';}
if(title == 'Page transition'){var videoSource = 'VkaRpFJTNEw';}