<?php
//activate
if (! function_exists('activate_ageCheck_addon')) {
    function activate_ageCheck_addon($StoreThemes, $shop) {
        foreach ($StoreThemes as $theme) {

            // Update schema file
            try{
                $schema = $shop->api()->request(
                    'GET',
                    '/admin/api/themes/'.$theme->shopify_theme_id.'/assets.json',
                    ['asset' => ['key' => 'config/settings_schema.json'] ]
                )['body']['asset']['value'] ?? '';

                $liveview_addon_schema = (string) '
                {
                    "name": "Age check",
                    "settings": [
                      {
                        "type": "checkbox",
                        "id": "dbtfy_age_check",
                        "label": "Activate",
                        "default": true
                      },
                      {
                        "type": "range",
                        "id": "dbtfy_age_check_valid_age",
                        "label": "Validate your age",
                        "min": 1,
                        "max": 31,
                        "default": 18
                      },
                      {
                        "type": "text",
                        "id": "dbtfy_ag_popup_animation",
                        "label": "Suffix"
                      },
                      {
                        "type": "image_picker",
                        "id": "dbtfy_age_check_logo_image",
                        "label": "Image"
                      },
                      {
                        "type": "text",
                        "id": "dbtfy_age_check_title",
                        "label": "Title"
                      },
                      {
                        "type": "text",
                        "id": "dbtfy_age_check_discription",
                        "label": "Description"
                      },
                      {
                        "type": "text",
                        "id": "dbtfy_age_check_error_message",
                        "label": "Error Message",
                        "default":   "Yes"
                      },
                      {
                        "type": "text",
                        "id": "dbtfy_age_check_enter",
                        "default":   "Check Age"
                      },
                      {
                         "type":      "radio",
                         "id":        "dbtfy_age_check_option",
                         "label":     "Birthdate",
                         "options": [
                           { "value": "birth-date", "label": "Choose Birthdate" },
                           { "value": "no", "label": "Selection" }
                         ],
                         "default":   "birth-date"
                      },
                      {
                        "type": "text",
                        "id": "dbtfy_age_check_yes",
                        "label": "Defult Check Age Yes",
                        "default":   "Yes"
                      },
                      {
                        "type": "text",
                        "id": "dbtfy_age_check_no",
                        "label": "Defult Check Age No",
                        "default":   "No"
                      },
                      {
                        "type": "image_picker",
                        "id": "dbtfy_age_check_background_image",
                        "label": "Image"
                      }
                    ]
                  }';

                if( ( $badgePos = strpos( $schema , 'dbtfy-age-check' ) ) === false ) {
                    if( ( $pos = strrpos( $schema , ']' ) ) !== false ) {
                        $updated_schema    = substr_replace( $schema , ",".$liveview_addon_schema."]" , $pos );
                        $update_schema_settings = $shop->api()->request(
                            'PUT',
                            '/admin/api/themes/'.$theme->shopify_theme_id.'/assets.json',
                            ['asset' => ['key' => 'config/settings_schema.json', 'value' => $updated_schema] ]
                        );
                    }
                }
            }
            catch(\GuzzleHttp\Exception\ClientException $e){
                logger('update schema on age check addon throws client exception');
            }
            catch(\Exception $e){
                logger('update schema on age check addon throws exception');
            }

            // add snippet
            try{
                $snippet = (string) '{%- comment -%}Please do not edit this file. Any modification can be lost as it is automatically updated by Debutify{%- endcomment -%}
                    {%- if settings.dbtfy_age_check -%}
                    <div class="dbtfy dbtfy-age_check" data-valid-age="{{ settings.dbtfy_age_check_valid_age }}">
                      <div id="AgeCheck" class="modal-ac-popup text-center animated fadeIn">
                        <div class="modal-dialog-ac-popup">
                          <div class="modal-content modal-content-ac-popup animated {{ settings.dbtfy_ag_popup_animation }}">

                            <div class="ac-modal-body">
                              {%- if settings.dbtfy_age_check_logo_image != blank -%}
                                <div class="ac-logo-img">
                                  <div class="image-wrapper animated fadeIn" style="padding-top:{{ 1 | divided_by: settings.dbtfy_age_check_logo_image.aspect_ratio | times: 100}}%;">
                                    {%- assign img_url = settings.dbtfy_age_check_logo_image | img_url: \'1x1\' | replace: \'_1x1.\', \'_{width}x.\' -%}
                                    <img class="image lazyload"
                                        data-src="{{ img_url }}"
                                        data-widths="[180, 360, 540, 720, 900, 1080, 1296, 1512, 1728, 2048]"
                                        data-aspectratio="{{ settings.dbtfy_age_check_logo_image.aspect_ratio }}"
                                        data-sizes="auto"
                                        alt="{{ settings.dbtfy_age_check_logo_image.alt | escape }}">
                                  </div>
                                </div>
                              {%- endif -%}

                              {%- if settings.dbtfy_age_check_title != blank -%}
                                <h1 class="ac-header">
                                  {{ settings.dbtfy_age_check_title }}
                                </h1>
                              {%- endif -%}

                              {%- if settings.dbtfy_age_check_discription != blank -%}
                                <p class="ac-adult-text">
                                  {{ settings.dbtfy_age_check_discription }}
                                </p>
                              {%- endif -%}

                              {%- if settings.dbtfy_age_check_error_message != blank -%}
                                <p class="ac-error-text">
                                  {{ settings.dbtfy_age_check_error_message }}
                                </p>
                              {%- endif -%}

                              {%- if settings.dbtfy_age_check_option == \'birth-date\' -%}
                                <div class="ac-date-picker inline-list">
                                  <select name="bmonth" id="bmonth" value="1" class="select--small full">
                                    <option value="1">Month</option>
                                    <option value="1">January</option>
                                    <option value="2">February</option>
                                    <option value="3">March</option>
                                    <option value="4">April</option>
                                    <option value="5">May</option>
                                    <option value="6">June</option>
                                    <option value="7">July</option>
                                    <option value="8">August</option>
                                    <option value="9">September</option>
                                    <option value="10">October</option>
                                    <option value="11">November</option>
                                    <option value="12">December</option>
                                  </select>

                                  <select name="bday" id="bday" value="1" class="select--small full">
                                    <option value="1">Day</option>

                                    {%- for i in (1..31) -%}
                                      <option value="{{ forloop.index }}">{{ i }}</option>
                                    {%- endfor -%}
                                  </select>

                                  <select name="byear" id="byear" value="1950" class="select--small full">
                                    <option value="2015">Year</option>

                                    {%- for i in (1910..2020) -%}
                                      <option value="{{ i }}">{{ i }}</option>
                                    {%- endfor -%}
                                  </select>
                                </div>

                              <button id="SubmitBirthdate" class="btn btn--primary full">{{ settings.dbtfy_age_check_enter }}</button>

                              {%- else -%}
                                <div class="ac-yes-no-option inline-list">
                                  <button type="button" class="btn btn--primary ac-yes">{{ settings.dbtfy_age_check_yes }}</button>
                                  <button type="button" class="btn btn--primary ac-no">{{ settings.dbtfy_age_check_no }}</button>
                                </div>
                              {%- endif -%}
                            </div>
                          </div>
                        </div>
                      </div>

                      {%- if settings.dbtfy_age_check_background_image != blank -%}
                        <div class="ac-popup-image-overlay lazyload"
                          data-bgset="{% include \'bgset\', image: settings.dbtfy_age_check_background_image %}"
                          data-sizes="auto"
                          data-parent-fit="cover">
                        </div>
                      {%- else -%}
                        <div class="ac-popup-overlay"></div>
                      {%- endif -%}
                    </div>
                    {% endif %}';

                $snippet = addScriptTagCondition($shop, '{%- comment -%}Please do not edit this file. Any modification can be lost as it is automatically updated by Debutify{%- endcomment -%}', $snippet);
                
                $create_ageCheck_snippet = $shop->api()->request(
                    'PUT',
                    '/admin/api/themes/'.$theme->shopify_theme_id.'/assets.json',
                    ['asset' => ['key' => 'snippets/dbtfy-age-check.liquid', 'value' => $snippet] ]
                );
            }
            catch(\GuzzleHttp\Exception\ClientException $e){
                logger('add age_check throws client exception');
            }
            catch(\Exception $e){
                logger('add age_check throws exception');
            }

            // add js addon
            try{
              $script= (string)'/* start-dbtfy-age-check */ function themeAgeCheck() { {%- if settings.dbtfy_age_check -%} var _0x6ef6=["\x2E\x64\x62\x74\x66\x79\x2D\x61\x67\x65\x5F\x63\x68\x65\x63\x6B","\x23\x41\x67\x65\x43\x68\x65\x63\x6B","\x2E\x63\x6C\x6F\x73\x65\x2D\x61\x63\x2D\x70\x6F\x70\x75\x70","\x23\x53\x75\x62\x6D\x69\x74\x42\x69\x72\x74\x68\x64\x61\x74\x65","\x2E\x61\x63\x2D\x61\x64\x75\x6C\x74\x2D\x74\x65\x78\x74","\x2E\x61\x63\x2D\x65\x72\x72\x6F\x72\x2D\x74\x65\x78\x74","\x62\x6F\x64\x79","\x64\x61\x74\x61\x2D\x76\x61\x6C\x69\x64\x2D\x61\x67\x65","\x61\x74\x74\x72","\x61\x63\x2D\x6F\x76\x65\x72\x66\x6C\x6F\x77\x2D\x68\x69\x64\x64\x65\x6E","\x72\x65\x6D\x6F\x76\x65\x43\x6C\x61\x73\x73","\x6F\x70\x65\x6E\x2D\x61\x63\x2D\x70\x6F\x70\x75\x70","\x68\x69\x64\x65","\x73\x68\x6F\x77","\x67\x65\x74\x54\x69\x6D\x65","\x73\x65\x74\x54\x69\x6D\x65","\x3B\x20\x65\x78\x70\x69\x72\x65\x73\x3D","\x74\x6F\x47\x4D\x54\x53\x74\x72\x69\x6E\x67","\x63\x6F\x6F\x6B\x69\x65","\x69\x73\x41\x6E\x41\x64\x75\x6C\x74\x3D\x74\x72\x75\x65\x3B","\x3B\x20\x70\x61\x74\x68\x3D\x2F","\x63\x6C\x69\x63\x6B","\x76\x61\x6C\x75\x65","\x62\x79\x65\x61\x72","\x67\x65\x74\x45\x6C\x65\x6D\x65\x6E\x74\x42\x79\x49\x64","\x62\x6D\x6F\x6E\x74\x68","\x62\x64\x61\x79","\x6F\x6E","\x2E\x61\x63\x2D\x79\x65\x73","\x2E\x61\x63\x2D\x6E\x6F","\x69\x73\x41\x6E\x41\x64\x75\x6C\x74","\x3D","\x3B","\x73\x70\x6C\x69\x74","\x6C\x65\x6E\x67\x74\x68","\x20","\x63\x68\x61\x72\x41\x74","\x73\x75\x62\x73\x74\x72\x69\x6E\x67","\x69\x6E\x64\x65\x78\x4F\x66","\x61\x64\x64\x43\x6C\x61\x73\x73"];function AgeCheckPopup(){var _0xebf7x2=$(_0x6ef6[0]),_0xebf7x3=$(_0x6ef6[1]),_0xebf7x4=$(_0x6ef6[2]),_0xebf7x5=$(_0x6ef6[3]),_0xebf7x6=$(_0x6ef6[4]),_0xebf7x7=$(_0x6ef6[5]),_0xebf7x8=$(_0x6ef6[6]),_0xebf7x9=parseInt(_0xebf7x2[_0x6ef6[8]](_0x6ef6[7]));function _0xebf7xa(){_0xebf7x8[_0x6ef6[10]](_0x6ef6[9]),_0xebf7x3[_0x6ef6[10]](_0x6ef6[11])}function _0xebf7xb(){void(0)!== _0xebf7x6&& _0xebf7x6[_0x6ef6[12]](),void(0)!== _0xebf7x7&& _0xebf7x7[_0x6ef6[13]]()}function _0xebf7xc(){var _0xebf7x2= new Date;_0xebf7x2[_0x6ef6[15]](_0xebf7x2[_0x6ef6[14]]()+ 6048e5);var _0xebf7x3=_0x6ef6[16]+ _0xebf7x2[_0x6ef6[17]]();document[_0x6ef6[18]]= _0x6ef6[19]+ _0xebf7x3+ _0x6ef6[20]}_0xebf7x4[_0x6ef6[21]](function(){_0xebf7xa()}),_0xebf7x5[_0x6ef6[27]](_0x6ef6[21],function(){var _0xebf7x2,_0xebf7x3,_0xebf7x4,_0xebf7x5;_0xebf7x2= parseInt(document[_0x6ef6[24]](_0x6ef6[23])[_0x6ef6[22]]),_0xebf7x3= parseInt(document[_0x6ef6[24]](_0x6ef6[25])[_0x6ef6[22]]),_0xebf7x4= parseInt(document[_0x6ef6[24]](_0x6ef6[26])[_0x6ef6[22]]),_0xebf7x5= new Date(_0xebf7x2+ _0xebf7x9,_0xebf7x3,_0xebf7x4),( new Date)[_0x6ef6[14]]()- _0xebf7x5[_0x6ef6[14]]()< 0?_0xebf7xb():(_0xebf7xc(),_0xebf7xa())}),$(_0x6ef6[28])[_0x6ef6[21]](function(){_0xebf7xc(),_0xebf7xa()}),$(_0x6ef6[29])[_0x6ef6[21]](function(){_0xebf7xb()}),function(_0xebf7x2){for(var _0xebf7x3=_0xebf7x2+ _0x6ef6[31],_0xebf7x4=document[_0x6ef6[18]][_0x6ef6[33]](_0x6ef6[32]),_0xebf7x5=0;_0xebf7x5< _0xebf7x4[_0x6ef6[34]];_0xebf7x5++){for(var _0xebf7x6=_0xebf7x4[_0xebf7x5];_0x6ef6[35]== _0xebf7x6[_0x6ef6[36]](0);){_0xebf7x6= _0xebf7x6[_0x6ef6[37]](1,_0xebf7x6[_0x6ef6[34]])};if(0== _0xebf7x6[_0x6ef6[38]](_0xebf7x3)){return _0xebf7x6[_0x6ef6[37]](_0xebf7x3[_0x6ef6[34]],_0xebf7x6[_0x6ef6[34]])}};return null}(_0x6ef6[30])?_0xebf7xa():(_0xebf7x8[_0x6ef6[39]](_0x6ef6[9]),_0xebf7x3[_0x6ef6[39]](_0x6ef6[11]))}AgeCheckPopup() {%- endif -%} } /* end-dbtfy-age-check */';

                // add js register
                $theme_js_content = $shop->api()->request(
                    'GET',
                    '/admin/api/themes/'.$theme->shopify_theme_id.'/assets.json',
                    ['asset' => ['key' => 'assets/dbtfy-addons.js.liquid'] ]
                )['body']['asset']['value'] ?? '';

                if( ( $pos = strpos( $theme_js_content , " /* start-register-age-check */" ) ) === false ) {
                        $new_theme_js = str_replace('var sections = new theme.Sections();', 'var sections = new theme.Sections(); /* start-register-age-check */themeAgeCheck();/* end-register-age-check */', $theme_js_content);

                    $add_js = $shop->api()->request(
                        'PUT',
                        '/admin/api/themes/'.$theme->shopify_theme_id.'/assets.json',
                        ['asset' => ['key' => 'assets/dbtfy-addons.js.liquid', 'value' => $new_theme_js] ]
                    );
                }

                $theme_js_content = $shop->api()->request(
                    'GET',
                    '/admin/api/themes/'.$theme->shopify_theme_id.'/assets.json',
                    ['asset' => ['key' => 'assets/dbtfy-addons.js.liquid'] ]
                )['body']['asset']['value'] ?? '';
                $replace_code= '/* start-dbtfy-addons */';
                if( ( $pos = strpos( $theme_js_content , 'start-dbtfy-age-check' ) ) === false ) {
                        $new_theme_js = str_replace($replace_code, $replace_code.$script, $theme_js_content);

                    $add_js = $shop->api()->request(
                        'PUT',
                        '/admin/api/themes/'.$theme->shopify_theme_id.'/assets.json',
                        ['asset' => ['key' => 'assets/dbtfy-addons.js.liquid', 'value' => $new_theme_js] ]
                    );
                }
            }
            catch(\GuzzleHttp\Exception\ClientException $e){
                logger('update js on age check addon throws client exception');
            }
            catch(\Exception $e){
                logger('update js on age check addon throws exception');
            }


            // add scss
            try{
                $styles = (string) '/* start-dbtfy-age-check */ {%if settings.dbtfy_age_check%}.dbtfy-age_check{overflow:hidden;.modal-ac-popup{padding:0 $gutter-sm;position:fixed;top:0;left:0;z-index:($zindexDrawer*4)+($zindexIncrement*4);width:100%;height:100%;overflow:hidden;outline:0;display:none;&.open-ac-popup{display:block;overflow-x:hidden;overflow-y:auto;&+.ac-popup-image-overlay{display:block}&+.ac-popup-overlay{display:block;pointer-events:auto;opacity:$colorDrawerOverlayOpacity}}}.modal-dialog-ac-popup{@include display-flexbox;@include align-items(center);@include justify-content(center);margin:$gutter 0;min-height:calc(100%-#{$gutter*2});pointer-events:none;width:100%}.modal-content-ac-popup{pointer-events:auto;background-color:$colorDrawer;border-radius:$borderRadius;overflow:hidden;color:$colorDrawerText;max-width:400px;width:100%;padding:$gutter;border-color:adaptive-color($colorDrawerDefault,$percentageColorBorder);h1{color:$colorDrawerText}.btn--primary{@include button($colorDrawerPrimary,$colorDrawerButtonText)}.ac-error-text{display:none;color:$colorDrawerPrimary}}.ac-popup-image-overlay{background-position:center center;background-size:cover;background-repeat:no-repeat;position:fixed;left:0;right:0;top:0;bottom:0;width:100%;height:100%;z-index:($zindexDrawer*2)+($zindexIncrement*2);display:none;&:after{content:"";background-color:$colorDrawerOverlay;opacity:$colorDrawerOverlayOpacity;position:fixed;left:0;right:0;top:0;bottom:0}}.ac-popup-overlay{background-color:$colorDrawerOverlay;position:fixed;left:0;right:0;top:0;bottom:0;width:100%;height:100%;opacity:0;pointer-events:none;z-index:($zindexDrawer*2)+($zindexIncrement*2);display:none;@include transition($transitionDrawers)}.ac-logo-img{margin-bottom:$spacer}}.ac-overflow-hidden{overflow:hidden} {%endif%} /* end-dbtfy-age-check */';
                $theme_style_content = $shop->api()->request(
                    'GET',
                    '/admin/api/themes/'.$theme->shopify_theme_id.'/assets.json',
                    ['asset' => ['key' => 'assets/theme.scss.liquid'] ]
                )['body']['asset']['value'] ?? '';

                if( ( $pos = strpos( $theme_style_content , 'start-dbtfy-age-check' ) ) === false ) {
                    $new_theme_styles = str_replace($theme_style_content, $theme_style_content.$styles, $theme_style_content);
                    $add_styles = $shop->api()->request(
                        'PUT',
                        '/admin/api/themes/'.$theme->shopify_theme_id.'/assets.json',
                        ['asset' => ['key' => 'assets/theme.scss.liquid', 'value' => $new_theme_styles] ]
                    );
                }
            }
            catch(\GuzzleHttp\Exception\ClientException $e){
                logger('update CSS on age_check addon throws client exception');
            }
            catch(\Exception $e){
                logger('update CSS on age_check addon throws exception');
            }


            // add include
            try{
                $product_template = $shop->api()->request(
                    'GET',
                    '/admin/api/themes/'.$theme->shopify_theme_id.'/assets.json',
                    ['asset' => ['key' => 'layout/theme.liquid'] ]
                )['body']['asset']['value'] ?? '';
                if( ( $pos = strrpos( $product_template , '{% include "dbtfy-age-check" %}' ) ) === false ) {
                    $new_prod_template = str_replace('</body>', '{% include "dbtfy-age-check" %} </body>', $product_template);
                    $update_prod_template = $shop->api()->request(
                        'PUT',
                        '/admin/api/themes/'.$theme->shopify_theme_id.'/assets.json',
                        ['asset' => ['key' => 'layout/theme.liquid', 'value' => $new_prod_template] ]
                    );
                }
            }
            catch(\GuzzleHttp\Exception\ClientException $e){
                logger('update instagram_feed on trustbadge addon throws client exception');
            }
            catch(\Exception $e){
                logger('update instagram_feed on trustbadge addon throws exception');
            }

        }
    }
}

// deactivate
if (! function_exists('deactivate_ageCheck_addon')) {
    function deactivate_ageCheck_addon($StoreThemes, $shop, $checkaddon) {
        foreach ($StoreThemes as $theme) {

            // remove schema
            $schema_get = $shop->api()->request(
                'GET',
                '/admin/api/themes/'.$theme->shopify_theme_id.'/assets.json',
                ['asset' => ['key' => 'config/settings_schema.json'] ]
            )['body'];

            if(!isset($schema_get['asset']['value']))
            {
                deactivate_ageCheck_addon_curl($theme, $shop);
                continue;
            }
            else
            {
                $schema = $schema_get['asset']['value'];
            }

            $json = json_decode($schema, true);
            $json = array_filter($json, function ($obj) {
              if (stripos($obj['name'], 'Age check') !== false) {
                  return false;
              }
              return true;
            });

            if(str_contains($schema,'Age check')){
                $value = json_encode(array_values($json));
                $updated_schema = $value;
                $update_schema_settings = $shop->api()->request(
                    'PUT',
                    '/admin/api/themes/'.$theme->shopify_theme_id.'/assets.json',
                    ['asset' => ['key' => 'config/settings_schema.json', 'value' => $updated_schema] ]
                );
            }

            // remove scss
            $theme_style_content = $shop->api()->request(
                'GET',
                '/admin/api/themes/'.$theme->shopify_theme_id.'/assets.json',
                ['asset' => ['key' => 'assets/theme.scss.liquid'] ]
            )['body']['asset']['value'] ?? '';

            $trustbadge_Style = (string) '/* start-dbtfy-age-check */';
            $end = (string) '/* end-dbtfy-age-check */';
            $string = ' ' . $theme_style_content;
            $ini = strpos($string, $trustbadge_Style);

            if ($ini == 0) {
              $parsed = '';
            }else{
              $ini += strlen($trustbadge_Style);
              $len = strpos($string, $end, $ini) - $ini;
              $parsed = substr($string, $ini, $len);
            }
            $values = $trustbadge_Style.''.$parsed.''.$end;

            if(str_contains($theme_style_content,'.dbtfy-age_check')){
                $value = str_replace($values, " ", $theme_style_content);
                $new_theme_styles = (string) $value;

                $update_styles = $shop->api()->request(
                    'PUT',
                    '/admin/api/themes/'.$theme->shopify_theme_id.'/assets.json',
                    ['asset' => ['key' => 'assets/theme.scss.liquid', 'value' => $new_theme_styles] ]
                );
            }

            // remove snippet
            $delete_trustbadge_snippet = $shop->api()->request(
                'DELETE',
                '/admin/api/themes/'.$theme->shopify_theme_id.'/assets.json',
                ['asset' => ['key' => 'snippets/dbtfy-age-check.liquid'] ]
            );

            // remove include
            $product_template = $shop->api()->request(
                'GET',
                '/admin/api/themes/'.$theme->shopify_theme_id.'/assets.json',
                ['asset' => ['key' => 'layout/theme.liquid'] ]
            )['body']['asset']['value'] ?? '';

            if(str_contains($product_template,"dbtfy-age-check")){
                $value  =  explode('{% include "dbtfy-age-check" %}',$product_template,2);

                if(isset($value[0]) && isset($value[1])){
                    $value = $value[0].' '.$value[1];
                }
                else {
                    $value = (string) $product_template;
                }

                $new_prod_template = (string) $value;

                $update_prod_template = $shop->api()->request(
                    'PUT',
                    '/admin/api/themes/'.$theme->shopify_theme_id.'/assets.json',
                    ['asset' => ['key' => 'layout/theme.liquid', 'value' => $new_prod_template] ]
                );
            }

            // remove js addon
            try{
               $theme_js_content = $shop->api()->request(
                    'GET',
                    '/admin/api/themes/'.$theme->shopify_theme_id.'/assets.json',
                    ['asset' => ['key' => 'assets/dbtfy-addons.js.liquid'] ]
                )['body']['asset']['value'] ?? '';

                $trustbadge_js = (string) '/* start-dbtfy-age-check */';
                $end_js = (string) '/* end-dbtfy-age-check */';
                $string_js = ' ' . $theme_js_content;
                $ini_js = strpos($string_js, $trustbadge_js);
                if ($ini_js == 0) {
                    $parsed_js = '';
                } else{
                    $ini_js += strlen($trustbadge_js);
                    $len_js = strpos($string_js, $end_js, $ini_js) - $ini_js;
                    $parsed_js = substr($string_js, $ini_js, $len_js);
                }
                $value_js = $trustbadge_js.''.$parsed_js.''.$end_js;
                if(!empty($theme_js_content) && str_contains($theme_js_content,'/* start-dbtfy-age-check */')){
                    $value = str_replace($value_js, " ", $theme_js_content);
                    $new_theme_js = (string) $value;
                    if(str_contains($new_theme_js,'/* start-register-age-check */')){
                        $trustbadge_js1 = (string) '/* start-register-age-check */';
                        $end_js = (string) '/* end-register-age-check */';
                        $string_js = ' ' . $new_theme_js;
                        $ini_js = strpos($string_js, $trustbadge_js1);
                        if ($ini_js == 0) {
                            $parsed_js = '';
                        } else{
                            $ini_js += strlen($trustbadge_js1);
                            $len_js = strpos($string_js, $end_js, $ini_js) - $ini_js;
                            $parsed_js = substr($string_js, $ini_js, $len_js);
                        }
                        $value_js = $trustbadge_js1.''.$parsed_js.''.$end_js;

                        $value = str_replace($value_js, " ", $new_theme_js);
                        $new_theme_js1 = (string) $value;
                        $update_js = $shop->api()->request(
                            'PUT',
                            '/admin/api/themes/'.$theme->shopify_theme_id.'/assets.json',
                            ['asset' => ['key' => 'assets/dbtfy-addons.js.liquid', 'value' => $new_theme_js1] ]
                        );
                    }
                    else{
                        $update_js = $shop->api()->request(
                            'PUT',
                            '/admin/api/themes/'.$theme->shopify_theme_id.'/assets.json',
                            ['asset' => ['key' => 'assets/dbtfy-addons.js.liquid', 'value' => $new_theme_js] ]
                        );
                    }
                }
            }
            catch(\GuzzleHttp\Exception\ClientException $e){
                logger('add age_check throws client exception');
            }
            catch(\Exception $e){
                logger('add age_check throws exception');
            }

        }
    }
}

// deactivate addon curl
if (! function_exists('deactivate_ageCheck_addon_curl')) {
    function deactivate_ageCheck_addon_curl($theme, $shop)
    {
        // remove schema
        $schema = getThemeFileCurl($shop, $theme, 'config/settings_schema.json');

        $json = json_decode($schema, true);
        $json = array_filter($json, function ($obj) {
            if (stripos($obj['name'], 'Age check') !== false) {
                return false;
            }
            return true;
        });

        if(str_contains($schema,'Age check')){
            $value = json_encode(array_values($json));
            $updated_schema = $value;
            $update_schema_settings = putThemeFileCurl($shop, $theme, $updated_schema, 'config/settings_schema.json');
        }

        // remove scss
        $theme_style_content = getThemeFileCurl($shop, $theme, 'assets/theme.scss.liquid');

        $trustbadge_Style = (string) '/* start-dbtfy-age-check */';
        $end = (string) '/* end-dbtfy-age-check */';
        $string = ' ' . $theme_style_content;
        $ini = strpos($string, $trustbadge_Style);

        if ($ini == 0) {
          $parsed = '';
        }else{
          $ini += strlen($trustbadge_Style);
          $len = strpos($string, $end, $ini) - $ini;
          $parsed = substr($string, $ini, $len);
        }
        $values = $trustbadge_Style.''.$parsed.''.$end;

        if(str_contains($theme_style_content,'.dbtfy-age_check')){
            $value = str_replace($values, " ", $theme_style_content);
            $new_theme_styles = (string) $value;

            $update_styles = putThemeFileCurl($shop, $theme, $new_theme_styles, 'assets/theme.scss.liquid');
        }

        // remove snippet
        $delete_trustbadge_snippet = deleteThemeFilesCurl($shop, $theme, 'snippets/dbtfy-age-check.liquid');

        // remove include
        $product_template = getThemeFileCurl($shop, $theme, 'layout/theme.liquid');

        if(str_contains($product_template,"dbtfy-age-check")){
            $value  =  explode('{% include "dbtfy-age-check" %}',$product_template,2);

            if(isset($value[0]) && isset($value[1])){
                $value = $value[0].' '.$value[1];
            }
            else {
                $value = (string) $product_template;
            }

            $new_prod_template = (string) $value;

            $update_prod_template = putThemeFileCurl($shop, $theme, $new_prod_template, 'layout/theme.liquid');
        }

        // remove js addon
        try{
           $theme_js_content = getThemeFileCurl($shop, $theme, 'assets/dbtfy-addons.js.liquid');
            if ($theme_js_content == null)
            {
                $theme_js_content = '';
            }
            $trustbadge_js = (string) '/* start-dbtfy-age-check */';
            $end_js = (string) '/* end-dbtfy-age-check */';
            $string_js = ' ' . $theme_js_content;
            $ini_js = strpos($string_js, $trustbadge_js);
            if ($ini_js == 0) {
                $parsed_js = '';
            } else{
                $ini_js += strlen($trustbadge_js);
                $len_js = strpos($string_js, $end_js, $ini_js) - $ini_js;
                $parsed_js = substr($string_js, $ini_js, $len_js);
            }
            $value_js = $trustbadge_js.''.$parsed_js.''.$end_js;
            if(!empty($theme_js_content) && str_contains($theme_js_content,'/* start-dbtfy-age-check */')){
                $value = str_replace($value_js, " ", $theme_js_content);
                $new_theme_js = (string) $value;
                if(str_contains($new_theme_js,'/* start-register-age-check */')){
                    $trustbadge_js1 = (string) '/* start-register-age-check */';
                    $end_js = (string) '/* end-register-age-check */';
                    $string_js = ' ' . $new_theme_js;
                    $ini_js = strpos($string_js, $trustbadge_js1);
                    if ($ini_js == 0) {
                        $parsed_js = '';
                    } else{
                        $ini_js += strlen($trustbadge_js1);
                        $len_js = strpos($string_js, $end_js, $ini_js) - $ini_js;
                        $parsed_js = substr($string_js, $ini_js, $len_js);
                    }
                    $value_js = $trustbadge_js1.''.$parsed_js.''.$end_js;

                    $value = str_replace($value_js, " ", $new_theme_js);
                    $new_theme_js1 = (string) $value;
                    $update_js = putThemeFileCurl($shop, $theme, $new_theme_js1, 'assets/dbtfy-addons.js.liquid');
                }
                else{
                    $update_js = putThemeFileCurl($shop, $theme, $new_theme_js, 'assets/dbtfy-addons.js.liquid');
                }
            }
        }
        catch(\GuzzleHttp\Exception\ClientException $e){
            logger('add age_check throws client exception');
        }
        catch(\Exception $e){
            logger('add age_check throws exception');
        }

    }
}
?>
