<?php
//activate
if (! function_exists('activate_cart_discount_addon')) {
    function activate_cart_discount_addon($StoreThemes, $shop) {
        foreach ($StoreThemes as $theme) {

            // Update schema file
            try{
                $schema = $shop->api()->request(
                    'GET',
                    '/admin/api/themes/'.$theme->shopify_theme_id.'/assets.json',
                    ['asset' => ['key' => 'config/settings_schema.json'] ]
                )['body']['asset']['value'] ?? '';

                $liveview_addon_schema = (string) '{
                    "name": "Cart discount",
                    "settings": [
                      {
                        "type": "header",
                        "content": "Activation"
                      },
                      {
                        "type": "checkbox",
                        "id": "dbtfy_cart_discount",
                        "label": "Activate",
                        "default": false
                      },
                      {
                        "type": "header",
                        "content": "Settings"
                      },
                      {
                        "type": "text",
                        "id": "dbtfy_cart_discount_label",
                        "label": "Input label"
                      },
                      {
                        "type": "text",
                        "id": "dbtfy_cart_discount_placeholder",
                        "label": "Input placeholder",
                        "default": "Enter coupon code here"
                      },
                      {
                        "type": "text",
                        "id": "dbtfy_cart_discount_apply_button_icon",
                        "label": "Button icon",
                        "default": "check-circle",
                        "info": "Enter the name of any free solid icons on [FontAwesome](https:\/\/fontawesome.com\/icons?d=gallery&s=solid&m=free)"
                      }
                    ]
                  }';

                if( ( $badgePos = strpos( $schema , 'dbtfy_cart_discount' ) ) === false ) {
                    if( ( $pos = strrpos( $schema , ']' ) ) !== false ) {
                        $updated_schema    = substr_replace( $schema , ",".$liveview_addon_schema."]" , $pos );
                        $update_schema_settings = $shop->api()->request(
                            'PUT',
                            '/admin/api/themes/'.$theme->shopify_theme_id.'/assets.json',
                            ['asset' => ['key' => 'config/settings_schema.json', 'value' => $updated_schema] ]
                        );
                    }
                }
            }
            catch(\GuzzleHttp\Exception\ClientException $e){
                logger('update schema on cart discount addon throws client exception');
            }
            catch(\Exception $e){
                logger('update schema on cart discount addon throws exception');
            }

            // add snippet
            try{
                $snippet = (string) '{%- comment -%}Please do not edit this file. Any modification can be lost as it is automatically updated by Debutify{%- endcomment -%}
                {%- if settings.dbtfy_cart_discount -%}
                <div class="dbtfy dbtfy-cart_discount">
                  <div class="CartDiscount">
                    {% unless settings.dbtfy_cart_discount_label == blank %}
                    <label for="discount">{{ settings.dbtfy_cart_discount_label }}</label>
                    {% endunless %}
                    <div class="input-group">
                      <input class="input-cart_discount input--small input-group-field" autocomplete="off" type="text" name="discount" placeholder="{{ settings.dbtfy_cart_discount_placeholder }}"/>
                      <span class="input-group-btn">
                        <button type="button" class="btn btn--primary btn--small cd-apply" name="apply-discount">
                          <span class="btn__text"><span class="fas fa-{{ settings.dbtfy_cart_discount_apply_button_icon }}" aria-hidden="true"></span></span>
                        </button>
                      </span>
                    </div>
                  </div>
                </div>
                {%- endif -%}';

                $snippet = addScriptTagCondition($shop, '{%- comment -%}Please do not edit this file. Any modification can be lost as it is automatically updated by Debutify{%- endcomment -%}', $snippet);

                $create_trustbadge_snippet = $shop->api()->request(
                    'PUT',
                    '/admin/api/themes/'.$theme->shopify_theme_id.'/assets.json',
                    ['asset' => ['key' => 'snippets/dbtfy-cart-discount.liquid', 'value' => $snippet] ]
                );
            }
            catch(\GuzzleHttp\Exception\ClientException $e){
                logger('add cart_discount throws client exception');
            }
            catch(\Exception $e){
                logger('add cart_discount throws exception');
            }

            // add js addon
            try{
              $script= (string)'/* start-dbtfy-cart-discount */ function themeCartDiscount() { {%- if settings.dbtfy_cart_discount -%} var _0xe77a=["\x6B\x65\x79\x64\x6F\x77\x6E","\x6B\x65\x79\x43\x6F\x64\x65","\x70\x72\x65\x76\x65\x6E\x74\x44\x65\x66\x61\x75\x6C\x74","","\x76\x61\x6C","\x63\x6C\x69\x63\x6B","\x74\x72\x69\x67\x67\x65\x72","\x62\x75\x74\x74\x6F\x6E\x5B\x6E\x61\x6D\x65\x3D\x27\x63\x68\x65\x63\x6B\x6F\x75\x74\x27\x5D","\x66\x69\x6E\x64","\x66\x6F\x72\x6D","\x63\x6C\x6F\x73\x65\x73\x74","\x74\x61\x72\x67\x65\x74","\x6F\x6E","\x2E\x69\x6E\x70\x75\x74\x2D\x63\x61\x72\x74\x5F\x64\x69\x73\x63\x6F\x75\x6E\x74","\x2E\x63\x64\x2D\x61\x70\x70\x6C\x79","\x2E\x43\x61\x72\x74\x44\x69\x73\x63\x6F\x75\x6E\x74"];function CartDiscount(){$(_0xe77a[13])[_0xe77a[12]](_0xe77a[0],function(_0x5620x2){13=== _0x5620x2[_0xe77a[1]]&& (_0x5620x2[_0xe77a[2]](),_0xe77a[3]!= $(this)[_0xe77a[4]]()&& $(_0x5620x2[_0xe77a[11]])[_0xe77a[10]](_0xe77a[9])[_0xe77a[8]](_0xe77a[7])[_0xe77a[6]](_0xe77a[5]))}),$(document)[_0xe77a[12]](_0xe77a[5],_0xe77a[14],function(_0x5620x2){_0x5620x2[_0xe77a[2]](),_0xe77a[3]!= $(_0x5620x2[_0xe77a[11]])[_0xe77a[10]](_0xe77a[15])[_0xe77a[8]](_0xe77a[13])[_0xe77a[4]]()&& $(_0x5620x2[_0xe77a[11]])[_0xe77a[10]](_0xe77a[9])[_0xe77a[8]](_0xe77a[7])[_0xe77a[6]](_0xe77a[5])})}CartDiscount() {%- endif -%} } /* end-dbtfy-cart-discount */';

                // add js register
                $theme_js_content = $shop->api()->request(
                    'GET',
                    '/admin/api/themes/'.$theme->shopify_theme_id.'/assets.json',
                    ['asset' => ['key' => 'assets/dbtfy-addons.js.liquid'] ]
                )['body']['asset']['value'] ?? '';

                if( ( $pos = strpos( $theme_js_content , "/* start-register-cart-discount */" ) ) === false ) {
                        $new_theme_js = str_replace('var sections = new theme.Sections();', 'var sections = new theme.Sections();/* start-register-cart-discount */themeCartDiscount();/* end-register-cart-discount */', $theme_js_content);

                    $add_js = $shop->api()->request(
                        'PUT',
                        '/admin/api/themes/'.$theme->shopify_theme_id.'/assets.json',
                        ['asset' => ['key' => 'assets/dbtfy-addons.js.liquid', 'value' => $new_theme_js] ]
                    );
                }

                $theme_js_content = $shop->api()->request(
                    'GET',
                    '/admin/api/themes/'.$theme->shopify_theme_id.'/assets.json',
                    ['asset' => ['key' => 'assets/dbtfy-addons.js.liquid'] ]
                )['body']['asset']['value'] ?? '';
                $replace_code= '/* start-dbtfy-addons */';
                if( ( $pos = strpos( $theme_js_content , 'start-dbtfy-cart-discount' ) ) === false ) {
                        $new_theme_js = str_replace($replace_code, $replace_code.$script, $theme_js_content);

                    $add_js = $shop->api()->request(
                        'PUT',
                        '/admin/api/themes/'.$theme->shopify_theme_id.'/assets.json',
                        ['asset' => ['key' => 'assets/dbtfy-addons.js.liquid', 'value' => $new_theme_js] ]
                    );
                }
            }catch(\GuzzleHttp\Exception\ClientException $e){
                logger('update js on cart discount addon throws client exception');
            }
            catch(\Exception $e){
                logger('update js on cart discount addon throws exception');
            }


            // add scss
            try{
                $styles = (string) '/* start-dbtfy-cart-discount */{% if settings.dbtfy_cart_discount %}.dbtfy-cart_discount{.CartDiscount{margin-bottom: $spacer;}input{display: block;width: 100%;margin-bottom: $spacer;&.input-group-field { margin-bottom: 0;}}label{font-size: $baseFontSize-sm;}.cd-apply{@include buttonSquareSmall;}}{% endif %}/* end-dbtfy-cart-discount */';

                $theme_style_content = $shop->api()->request(
                    'GET',
                    '/admin/api/themes/'.$theme->shopify_theme_id.'/assets.json',
                    ['asset' => ['key' => 'assets/theme.scss.liquid'] ]
                )['body']['asset']['value'] ?? '';

                if( ( $pos = strpos( $theme_style_content , 'start-dbtfy-cart-discount' ) ) === false ) {
                    $new_theme_styles = str_replace($theme_style_content, $theme_style_content.$styles, $theme_style_content);
                    $add_styles = $shop->api()->request(
                        'PUT',
                        '/admin/api/themes/'.$theme->shopify_theme_id.'/assets.json',
                        ['asset' => ['key' => 'assets/theme.scss.liquid', 'value' => $new_theme_styles] ]
                    );
                }
            }
            catch(\GuzzleHttp\Exception\ClientException $e){
                logger('update CSS on cart_discount addon throws client exception');
            }
            catch(\Exception $e){
                logger('update CSS on cart_discount addon throws exception');
            }

            // add include
            try{
                $product_template = $shop->api()->request(
                    'GET',
                    '/admin/api/themes/'.$theme->shopify_theme_id.'/assets.json',
                    ['asset' => ['key' => 'templates/cart.liquid'] ]
                )['body']['asset']['value'] ?? '';

                if( ( $pos = strpos( $product_template , 'dbtfy-cart-discount' ) ) === false ) {
                    if( ( $pos = strrpos( $product_template , '<button type="submit" name="checkout"' ) ) !== false ) {
                        $new_prod_template = str_replace('<button type="submit" name="checkout"', '{% include "dbtfy-cart-discount" %}<button type="submit" name="checkout"', $product_template);
                        $update_prod_template = $shop->api()->request(
                            'PUT',
                            '/admin/api/themes/'.$theme->shopify_theme_id.'/assets.json',
                            ['asset' => ['key' => 'templates/cart.liquid', 'value' => $new_prod_template] ]
                        );
                    }
                }
            }
            catch(\GuzzleHttp\Exception\ClientException $e){
                logger('update cart discount include throws client exception');
            }
            catch(\Exception $e){
                logger('update cart discount include throws exception');
            }

            // add include
            try{
                $product_template = $shop->api()->request(
                    'GET',
                    '/admin/api/themes/'.$theme->shopify_theme_id.'/assets.json',
                    ['asset' => ['key' => 'snippets/ajax-cart-template.liquid'] ]
                )['body']['asset']['value'] ?? '';

                if( ( $pos = strpos( $product_template , 'dbtfy-cart-discount' ) ) === false ) {
                    if( ( $pos = strrpos( $product_template , '<button type="submit"' ) ) !== false ) {
                        $new_prod_template = str_replace('<button type="submit"', '{% endraw %}{% include "dbtfy-cart-discount" %}{% raw %}<button type="submit"', $product_template);
                        $update_prod_template = $shop->api()->request(
                            'PUT',
                            '/admin/api/themes/'.$theme->shopify_theme_id.'/assets.json',
                            ['asset' => ['key' => 'snippets/ajax-cart-template.liquid', 'value' => $new_prod_template] ]
                        );
                    }
                }
            }
            catch(\GuzzleHttp\Exception\ClientException $e){
                logger('update cart discount include throws client exception');
            }
            catch(\Exception $e){
                logger('update cart discount include throws exception');
            }

        }
    }
}

// deactivate
if (! function_exists('deactivate_cart_discount_addon')) {
    function deactivate_cart_discount_addon($StoreThemes, $shop, $checkaddon) {
        foreach ($StoreThemes as $theme) {

            // remove schema
            $schema_get = $shop->api()->request(
                'GET',
                '/admin/api/themes/'.$theme->shopify_theme_id.'/assets.json',
                ['asset' => ['key' => 'config/settings_schema.json'] ]
            )['body'];

            if(!isset($schema_get['asset']['value']))
            {
                deactivate_cart_discount_addon_curl($theme, $shop);
                continue;
            }
            else
            {
                $schema = $schema_get['asset']['value'];
            }

            $json = json_decode($schema, true);
            $json = array_filter($json, function ($obj) {
              if (stripos($obj['name'], 'Cart discount') !== false) {
                  return false;
              }
              return true;
            });

            if(!empty($schema) && str_contains($schema,'Cart discount')){
                $value = json_encode(array_values($json));
                $updated_schema = $value;
                $update_schema_settings = $shop->api()->request(
                    'PUT',
                    '/admin/api/themes/'.$theme->shopify_theme_id.'/assets.json',
                    ['asset' => ['key' => 'config/settings_schema.json', 'value' => $updated_schema] ]
                );
            }

            // remove scss
            $theme_style_content = $shop->api()->request(
                'GET',
                '/admin/api/themes/'.$theme->shopify_theme_id.'/assets.json',
                ['asset' => ['key' => 'assets/theme.scss.liquid'] ]
            )['body']['asset']['value'] ?? '';

            $trustbadge_Style = (string) '/* start-dbtfy-cart-discount */';
            $end = (string) '/* end-dbtfy-cart-discount */';
            $string = ' ' . $theme_style_content;
            $ini = strpos($string, $trustbadge_Style);

            if ($ini == 0) {
              $parsed = '';
            }else{
              $ini += strlen($trustbadge_Style);
              $len = strpos($string, $end, $ini) - $ini;
              $parsed = substr($string, $ini, $len);
            }
            $values = $trustbadge_Style.''.$parsed.''.$end;

            if(!empty($theme_style_content) && str_contains($theme_style_content,'.dbtfy-cart_discount')){
                $value = str_replace($values, " ", $theme_style_content);
                $new_theme_styles = (string) $value;

                $update_styles = $shop->api()->request(
                    'PUT',
                    '/admin/api/themes/'.$theme->shopify_theme_id.'/assets.json',
                    ['asset' => ['key' => 'assets/theme.scss.liquid', 'value' => $new_theme_styles] ]
                );
            }

            // remove snippet
            $delete_trustbadge_snippet = $shop->api()->request(
                'DELETE',
                '/admin/api/themes/'.$theme->shopify_theme_id.'/assets.json',
                ['asset' => ['key' => 'snippets/dbtfy-cart-discount.liquid'] ]
            );

            // remove include - cart.liquid
             $product_template = $shop->api()->request(
                'GET',
                '/admin/api/themes/'.$theme->shopify_theme_id.'/assets.json',
                ['asset' => ['key' => 'templates/cart.liquid'] ]
            )['body']['asset']['value'] ?? '';
            if(!empty($product_template) && str_contains($product_template,'dbtfy-cart-discount')){
                $value  =  explode('{% include "dbtfy-cart-discount" %}',$product_template,2);

                if(isset($value[0]) && isset($value[1])){
                    $value = $value[0].' '.$value[1];
                }
                else{
                    $value = (string) $product_template;
                }

                 $new_prod_template = (string) $value;
                     $update_prod_template = $shop->api()->request(
                    'PUT',
                    '/admin/api/themes/'.$theme->shopify_theme_id.'/assets.json',
                    ['asset' => ['key' => 'templates/cart.liquid', 'value' => $new_prod_template] ]
                );
            }

            // remove include - ajax-cart-template.liquid
            $product_template = $shop->api()->request(
                'GET',
                '/admin/api/themes/'.$theme->shopify_theme_id.'/assets.json',
                ['asset' => ['key' => 'snippets/ajax-cart-template.liquid'] ]
            )['body']['asset']['value'] ?? '';

            if(!empty($product_template) && str_contains((string) $product_template,'dbtfy-cart-discount')){
                $value  =  explode('{% endraw %}{% include "dbtfy-cart-discount" %}{% raw %}',$product_template,2);

                if(isset($value[0]) && isset($value[1])){
                    $value = $value[0].' '.$value[1];
                }
                else{
                    $value = (string) $product_template;
                }

                $new_prod_template = (string) $value;
                $update_prod_template = $shop->api()->request(
                    'PUT',
                    '/admin/api/themes/'.$theme->shopify_theme_id.'/assets.json',
                    ['asset' => ['key' => 'snippets/ajax-cart-template.liquid', 'value' => $new_prod_template] ]
                );
            }

            // remove js addon
            try{
               $theme_js_content = $shop->api()->request(
                    'GET',
                    '/admin/api/themes/'.$theme->shopify_theme_id.'/assets.json',
                    ['asset' => ['key' => 'assets/dbtfy-addons.js.liquid'] ]
                )['body']['asset']['value'] ?? '';

                $trustbadge_js = (string) '/* start-dbtfy-cart-discount */';
                $end_js = (string) '/* end-dbtfy-cart-discount */';
                $string_js = ' ' . $theme_js_content;
                $ini_js = strpos($string_js, $trustbadge_js);
                if ($ini_js == 0) {
                    $parsed_js = '';
                } else{
                    $ini_js += strlen($trustbadge_js);
                    $len_js = strpos($string_js, $end_js, $ini_js) - $ini_js;
                    $parsed_js = substr($string_js, $ini_js, $len_js);
                }
                $value_js = $trustbadge_js.''.$parsed_js.''.$end_js;
                if(!empty($theme_js_content) && str_contains($theme_js_content,'/* start-dbtfy-cart-discount */')){
                    $value = str_replace($value_js, " ", $theme_js_content);
                    $new_theme_js = (string) $value;
                    if(!empty($new_theme_js) && str_contains($new_theme_js,'/* start-register-cart-discount */')){
                        $trustbadge_js1 = (string) '/* start-register-cart-discount */';
                        $end_js = (string) '/* end-register-cart-discount */';
                        $string_js = ' ' . $new_theme_js;
                        $ini_js = strpos($string_js, $trustbadge_js1);
                        if ($ini_js == 0) {
                            $parsed_js = '';
                        } else{
                            $ini_js += strlen($trustbadge_js1);
                            $len_js = strpos($string_js, $end_js, $ini_js) - $ini_js;
                            $parsed_js = substr($string_js, $ini_js, $len_js);
                        }
                        $value_js = $trustbadge_js1.''.$parsed_js.''.$end_js;

                        $value = str_replace($value_js, " ", $new_theme_js);
                        $new_theme_js1 = (string) $value;
                        $update_js = $shop->api()->request(
                            'PUT',
                            '/admin/api/themes/'.$theme->shopify_theme_id.'/assets.json',
                            ['asset' => ['key' => 'assets/dbtfy-addons.js.liquid', 'value' => $new_theme_js1] ]
                        );
                    }
                    else{
                        $update_js = $shop->api()->request(
                            'PUT',
                            '/admin/api/themes/'.$theme->shopify_theme_id.'/assets.json',
                            ['asset' => ['key' => 'assets/dbtfy-addons.js.liquid', 'value' => $new_theme_js] ]
                        );
                    }
                }
            }
            catch(\GuzzleHttp\Exception\ClientException $e){
                logger('add cart_discount throws client exception');
            }
            catch(\Exception $e){
                logger('add cart_discount throws exception');
            }

        }
    }
}


if (! function_exists('deactivate_cart_discount_addon_curl')) {
    function deactivate_cart_discount_addon_curl($theme, $shop)
    {
        $schema = getThemeFileCurl($shop, $theme, 'config/settings_schema.json');

        $json = json_decode($schema, true);
        $json = array_filter($json, function ($obj) {
          if (stripos($obj['name'], 'Cart discount') !== false) {
              return false;
          }
          return true;
        });

        if(!empty($schema) && str_contains($schema,'Cart discount')){
            $value = json_encode(array_values($json));
            $updated_schema = $value;
            $update_schema_settings = putThemeFileCurl($shop, $theme, $updated_schema, 'config/settings_schema.json');
        }

        // remove scss
        $theme_style_content = getThemeFileCurl($shop, $theme, 'assets/theme.scss.liquid');

        $trustbadge_Style = (string) '/* start-dbtfy-cart-discount */';
        $end = (string) '/* end-dbtfy-cart-discount */';
        $string = ' ' . $theme_style_content;
        $ini = strpos($string, $trustbadge_Style);

        if ($ini == 0) {
          $parsed = '';
        }else{
          $ini += strlen($trustbadge_Style);
          $len = strpos($string, $end, $ini) - $ini;
          $parsed = substr($string, $ini, $len);
        }
        $values = $trustbadge_Style.''.$parsed.''.$end;

        if(!empty($theme_style_content) && str_contains($theme_style_content,'.dbtfy-cart_discount')){
            $value = str_replace($values, " ", $theme_style_content);
            $new_theme_styles = (string) $value;

            $update_styles = putThemeFileCurl($shop, $theme, $new_theme_styles, 'assets/theme.scss.liquid');
        }

        // remove snippet
        $delete_trustbadge_snippet = deleteThemeFilesCurl($shop, $theme, 'snippets/dbtfy-cart-discount.liquid');

        // remove include - cart.liquid
        $product_template = getThemeFileCurl($shop, $theme, 'templates/cart.liquid');

        if(!empty($product_template) && str_contains($product_template,'dbtfy-cart-discount')){
            $value  =  explode('{% include "dbtfy-cart-discount" %}',$product_template,2);

            if(isset($value[0]) && isset($value[1])){
                $value = $value[0].' '.$value[1];
            }
            else{
                $value = (string) $product_template;
            }

            $new_prod_template = (string) $value;
            $update_prod_template = putThemeFileCurl($shop, $theme, $new_prod_template, 'templates/cart.liquid');
        }

        // remove include - ajax-cart-template.liquid
        $product_template = getThemeFileCurl($shop, $theme, 'snippets/ajax-cart-template.liquid');

        if(!empty($product_template) && str_contains($product_template,'dbtfy-cart-discount')){
            $value  =  explode('{% endraw %}{% include "dbtfy-cart-discount" %}{% raw %}',$product_template,2);

            if(isset($value[0]) && isset($value[1])){
                $value = $value[0].' '.$value[1];
            }
            else{
                $value = (string) $product_template;
            }

            $new_prod_template = (string) $value;
            $update_prod_template = putThemeFileCurl($shop, $theme, $new_prod_template, 'snippets/ajax-cart-template.liquid');
        }

        // remove js addon
        try{
           $theme_js_content = getThemeFileCurl($shop, $theme, 'assets/dbtfy-addons.js.liquid');
            if ($theme_js_content == null)
            {
                $theme_js_content = '';
            }
            $trustbadge_js = (string) '/* start-dbtfy-cart-discount */';
            $end_js = (string) '/* end-dbtfy-cart-discount */';
            $string_js = ' ' . $theme_js_content;
            $ini_js = strpos($string_js, $trustbadge_js);
            if ($ini_js == 0) {
                $parsed_js = '';
            } else{
                $ini_js += strlen($trustbadge_js);
                $len_js = strpos($string_js, $end_js, $ini_js) - $ini_js;
                $parsed_js = substr($string_js, $ini_js, $len_js);
            }
            $value_js = $trustbadge_js.''.$parsed_js.''.$end_js;
            if(!empty($theme_js_content) && str_contains($theme_js_content,'/* start-dbtfy-cart-discount */')){
                $value = str_replace($value_js, " ", $theme_js_content);
                $new_theme_js = (string) $value;
                if(!empty($new_theme_js) && str_contains($new_theme_js,'/* start-register-cart-discount */')){
                    $trustbadge_js1 = (string) '/* start-register-cart-discount */';
                    $end_js = (string) '/* end-register-cart-discount */';
                    $string_js = ' ' . $new_theme_js;
                    $ini_js = strpos($string_js, $trustbadge_js1);
                    if ($ini_js == 0) {
                        $parsed_js = '';
                    } else{
                        $ini_js += strlen($trustbadge_js1);
                        $len_js = strpos($string_js, $end_js, $ini_js) - $ini_js;
                        $parsed_js = substr($string_js, $ini_js, $len_js);
                    }
                    $value_js = $trustbadge_js1.''.$parsed_js.''.$end_js;

                    $value = str_replace($value_js, " ", $new_theme_js);
                    $new_theme_js1 = (string) $value;
                    $update_js = putThemeFileCurl($shop, $theme, $new_theme_js1, 'assets/dbtfy-addons.js.liquid');
                }
                else{
                    $update_js = putThemeFileCurl($shop, $theme, $new_theme_js, 'assets/dbtfy-addons.js.liquid');
                }
            }
        }
        catch(\GuzzleHttp\Exception\ClientException $e){
            logger('add cart_discount throws client exception');
        }
        catch(\Exception $e){
            logger('add cart_discount throws exception');
        }

    }
}
?>
