<?php
//activate
if (! function_exists('activate_product_video_addon')) {
    function activate_product_video_addon($StoreThemes, $shop) {
        foreach ($StoreThemes as $theme) {

            // Update schema file
            try{
                $schema = $shop->api()->request(
                    'GET',
                    '/admin/api/themes/'.$theme->shopify_theme_id.'/assets.json',
                    ['asset' => ['key' => 'config/settings_schema.json'] ]
                )['body']['asset']['value'] ?? '';

                $liveview_addon_schema = (string) '{
    "name": "Product video",
    "settings": [
      {
        "type": "header",
        "content": "Activation"
      },
      {
        "type": "checkbox",
        "id": "dbtfy_product_video",
        "label": "Activate",
        "default": false,
        "info": "Youtube, Vimeo & Dailymotion"
      },
      {
        "type": "paragraph",
        "content": "Add your video link to your product image alt text. [Edit product alt text](\/admin\/products)."
      },
      {
        "type": "header",
        "content": "Settings"
      },
      {
        "type": "checkbox",
        "id": "dbtfy_product_video_autoplay",
        "label": "Autoplay video",
        "default": true
      },
      {
        "type": "select",
        "id": "dbtfy_product_video_animation",
        "label": "Animation type",
        "default": "bounceIn",
        "options": [
          {
            "value": "bounceIn",
            "label": "Bounce in"
          },
          {
            "value": "fadeIn",
            "label": "Fade In"
          },
          {
            "value": "fadeInDown",
            "label": "Fade In Down"
          },
          {
            "value": "fadeInUp",
            "label": "Fade In Up"
          }
        ]
      }
    ]
  }';

                if( ( $badgePos = strpos( $schema , 'dbtfy_product_video' ) ) === false ) {
                    if( ( $pos = strrpos( $schema , ']' ) ) !== false ) {
                        $updated_schema    = substr_replace( $schema , ",".$liveview_addon_schema."]" , $pos );
                        $update_schema_settings = $shop->api()->request(
                            'PUT',
                            '/admin/api/themes/'.$theme->shopify_theme_id.'/assets.json',
                            ['asset' => ['key' => 'config/settings_schema.json', 'value' => $updated_schema] ]
                        );
                    }
                }
            }
            catch(\GuzzleHttp\Exception\ClientException $e){
                logger('update schema on live view addon throws client exception');
            }
            catch(\Exception $e){
                logger('update schema on live view addon throws exception');
            }

            // add snippet
            try{
                $snippet = (string) '{%- comment -%}Please do not edit this file. Any modification can be lost as it is automatically updated by Debutify{%- endcomment -%}
{%- if settings.dbtfy_product_video -%}
<div class="dbtfy dbtfy-product_video"
     data-autoplay="{{ settings.dbtfy_product_video_autoplay }}"
     data-color="{{ settings.color_secondary | remove: "#" | uppercase }}">
  <div id="ProductVideo" class="animated {{ settings.dbtfy_product_video_animation }}" style="display:none;">
    <div class="container-product_video"></div>
  </div>
</div>
{%- endif -%}';

                $snippet = addScriptTagCondition($shop, '{%- comment -%}Please do not edit this file. Any modification can be lost as it is automatically updated by Debutify{%- endcomment -%}', $snippet);

                $create_trustbadge_snippet = $shop->api()->request(
                    'PUT',
                    '/admin/api/themes/'.$theme->shopify_theme_id.'/assets.json',
                    ['asset' => ['key' => 'snippets/dbtfy-product-video.liquid', 'value' => $snippet] ]
                );
            }
            catch(\GuzzleHttp\Exception\ClientException $e){
                logger('add product_video throws client exception');
            }
            catch(\Exception $e){
                logger('add product_video throws exception');
            }

            // add js addon
            try{
              $script= (string)'/* start-dbtfy-product-video */function themeProductVideo() { {% if settings.dbtfy_product_video %} var _0x2393=["\x2E\x64\x62\x74\x66\x79\x2D\x70\x72\x6F\x64\x75\x63\x74\x5F\x76\x69\x64\x65\x6F","\x61\x75\x74\x6F\x70\x6C\x61\x79","\x64\x61\x74\x61","\x63\x6F\x6C\x6F\x72","\x6A\x73\x2D\x64\x72\x61\x77\x65\x72\x2D\x6F\x70\x65\x6E\x20\x6A\x73\x2D\x64\x72\x61\x77\x65\x72\x2D\x6F\x70\x65\x6E\x2D\x76\x69\x64\x65\x6F","\x6D\x61\x74\x63\x68","\x79\x6F\x75\x74\x75","\x69\x6E\x64\x65\x78\x4F\x66","\x24\x33","\x79\x6F\x75\x74\x75\x62\x65","\x76\x69\x6D\x65\x6F","\x64\x61\x69\x6C\x79\x6D\x6F\x74\x69\x6F\x6E","\x24\x36","\x3C\x69\x66\x72\x61\x6D\x65\x3E","\x26\x63\x6F\x6C\x6F\x72\x3D","\x3F\x61\x75\x74\x6F\x70\x6C\x61\x79\x3D\x31","\x3F\x63\x6F\x6C\x6F\x72\x3D","","\x66\x72\x61\x6D\x65\x62\x6F\x72\x64\x65\x72","\x61\x74\x74\x72","\x61\x6C\x6C\x6F\x77\x66\x75\x6C\x6C\x73\x63\x72\x65\x65\x6E","\x74\x79\x70\x65","\x73\x72\x63","\x2F\x2F\x77\x77\x77\x2E\x79\x6F\x75\x74\x75\x62\x65\x2E\x63\x6F\x6D\x2F\x65\x6D\x62\x65\x64\x2F","\x69\x64","\x61\x6C\x6C\x6F\x77","\x61\x63\x63\x65\x6C\x65\x72\x6F\x6D\x65\x74\x65\x72\x3B\x20\x61\x75\x74\x6F\x70\x6C\x61\x79\x3B\x20\x65\x6E\x63\x72\x79\x70\x74\x65\x64\x2D\x6D\x65\x64\x69\x61\x3B\x20\x67\x79\x72\x6F\x73\x63\x6F\x70\x65\x3B\x20\x70\x69\x63\x74\x75\x72\x65\x2D\x69\x6E\x2D\x70\x69\x63\x74\x75\x72\x65","\x2F\x2F\x70\x6C\x61\x79\x65\x72\x2E\x76\x69\x6D\x65\x6F\x2E\x63\x6F\x6D\x2F\x76\x69\x64\x65\x6F\x2F","\x66\x75\x6C\x6C\x73\x63\x72\x65\x65\x6E\x3B\x61\x75\x74\x6F\x70\x6C\x61\x79","\x66\x75\x6C\x6C\x73\x63\x72\x65\x65\x6E","\x2F\x2F\x77\x77\x77\x2E\x64\x61\x69\x6C\x79\x6D\x6F\x74\x69\x6F\x6E\x2E\x63\x6F\x6D\x2F\x65\x6D\x62\x65\x64\x2F\x76\x69\x64\x65\x6F\x2F","\x72\x65\x6D\x6F\x76\x65\x43\x6C\x61\x73\x73","\x62\x6F\x64\x79","\x68\x69\x64\x65","\x23\x50\x72\x6F\x64\x75\x63\x74\x56\x69\x64\x65\x6F","\x72\x65\x6D\x6F\x76\x65","\x2E\x63\x6F\x6E\x74\x61\x69\x6E\x65\x72\x2D\x70\x72\x6F\x64\x75\x63\x74\x5F\x76\x69\x64\x65\x6F\x20\x69\x66\x72\x61\x6D\x65","\x76\x69\x64\x65\x6F\x2D\x74\x68\x75\x6D\x62\x6E\x61\x69\x6C","\x61\x64\x64\x43\x6C\x61\x73\x73","\x2E\x70\x72\x6F\x64\x75\x63\x74\x2D\x73\x69\x6E\x67\x6C\x65\x5F\x5F\x70\x68\x6F\x74\x6F\x2D\x77\x72\x61\x70\x70\x65\x72","\x63\x6C\x6F\x73\x65\x73\x74","\x2E\x70\x72\x6F\x64\x75\x63\x74\x2D\x73\x69\x6E\x67\x6C\x65\x20\x2E\x70\x72\x6F\x64\x75\x63\x74\x2D\x73\x69\x6E\x67\x6C\x65\x5F\x5F\x70\x68\x6F\x74\x6F\x5B\x61\x6C\x74\x2A\x3D\x27\x79\x6F\x75\x74\x75\x27\x5D\x2C\x2E\x70\x72\x6F\x64\x75\x63\x74\x2D\x73\x69\x6E\x67\x6C\x65\x20\x2E\x70\x72\x6F\x64\x75\x63\x74\x2D\x73\x69\x6E\x67\x6C\x65\x5F\x5F\x70\x68\x6F\x74\x6F\x5B\x61\x6C\x74\x2A\x3D\x27\x76\x69\x6D\x65\x6F\x27\x5D\x2C\x2E\x70\x72\x6F\x64\x75\x63\x74\x2D\x73\x69\x6E\x67\x6C\x65\x20\x2E\x70\x72\x6F\x64\x75\x63\x74\x2D\x73\x69\x6E\x67\x6C\x65\x5F\x5F\x70\x68\x6F\x74\x6F\x5B\x61\x6C\x74\x2A\x3D\x27\x64\x61\x69\x6C\x79\x6D\x6F\x74\x69\x6F\x6E\x27\x5D","\x2E\x70\x72\x6F\x64\x75\x63\x74\x2D\x73\x69\x6E\x67\x6C\x65\x5F\x5F\x74\x68\x75\x6D\x62\x6E\x61\x69\x6C","\x2E\x70\x72\x6F\x64\x75\x63\x74\x2D\x73\x69\x6E\x67\x6C\x65\x20\x2E\x70\x72\x6F\x64\x75\x63\x74\x2D\x73\x69\x6E\x67\x6C\x65\x5F\x5F\x74\x68\x75\x6D\x62\x5B\x61\x6C\x74\x2A\x3D\x27\x79\x6F\x75\x74\x75\x27\x5D\x2C\x2E\x70\x72\x6F\x64\x75\x63\x74\x2D\x73\x69\x6E\x67\x6C\x65\x20\x2E\x70\x72\x6F\x64\x75\x63\x74\x2D\x73\x69\x6E\x67\x6C\x65\x5F\x5F\x74\x68\x75\x6D\x62\x5B\x61\x6C\x74\x2A\x3D\x27\x76\x69\x6D\x65\x6F\x27\x5D\x2C\x2E\x70\x72\x6F\x64\x75\x63\x74\x2D\x73\x69\x6E\x67\x6C\x65\x20\x2E\x70\x72\x6F\x64\x75\x63\x74\x2D\x73\x69\x6E\x67\x6C\x65\x5F\x5F\x74\x68\x75\x6D\x62\x5B\x61\x6C\x74\x2A\x3D\x27\x64\x61\x69\x6C\x79\x6D\x6F\x74\x69\x6F\x6E\x27\x5D","\x63\x6C\x69\x63\x6B","\x61\x6C\x74","\x69\x6D\x67","\x66\x69\x6E\x64","\x68\x74\x6D\x6C","\x2E\x63\x6F\x6E\x74\x61\x69\x6E\x65\x72\x2D\x70\x72\x6F\x64\x75\x63\x74\x5F\x76\x69\x64\x65\x6F","\x73\x68\x6F\x77","\x6F\x6E","\x2E\x70\x72\x6F\x64\x75\x63\x74\x2D\x73\x69\x6E\x67\x6C\x65\x20\x2E\x70\x72\x6F\x64\x75\x63\x74\x2D\x73\x69\x6E\x67\x6C\x65\x5F\x5F\x70\x68\x6F\x74\x6F\x2D\x77\x72\x61\x70\x70\x65\x72\x2E\x76\x69\x64\x65\x6F\x2D\x74\x68\x75\x6D\x62\x6E\x61\x69\x6C","\x6B\x65\x79\x43\x6F\x64\x65","\x6B\x65\x79\x75\x70"];function ProductVideo(){var _0xcf47x2=$(_0x2393[0]),_0xcf47x3=_0xcf47x2[_0x2393[2]](_0x2393[1]),_0xcf47x4=_0xcf47x2[_0x2393[2]](_0x2393[3]),_0xcf47x5=_0x2393[4];function _0xcf47x6(_0xcf47x2,_0xcf47x5,_0xcf47x6){var _0xcf47x7=function(_0xcf47x2){if(_0xcf47x2[_0x2393[5]](/(http:|https:|)\/\/(player.|www.)?(vimeo\.com|youtu(be\.com|\.be|be\.googleapis\.com)|dailymotion.com)\/(video\/|embed\/|watch\?v=|v\/)?([A-Za-z0-9._%-]*)(\&\S+)?/),-1< RegExp[_0x2393[8]][_0x2393[7]](_0x2393[6])){var _0xcf47x5=_0x2393[9]}else {if(-1< RegExp[_0x2393[8]][_0x2393[7]](_0x2393[10])){_0xcf47x5= _0x2393[10]}else {if(-1< RegExp[_0x2393[8]][_0x2393[7]](_0x2393[11])){_0xcf47x5= _0x2393[11]}}};return {type:_0xcf47x5,id:RegExp[_0x2393[12]]}}(_0xcf47x2),_0xcf47x8=$(_0x2393[13],{width:_0xcf47x5,height:_0xcf47x6});if(_0xcf47x3){var _0xcf47x9=_0x2393[14]+ _0xcf47x4,_0xcf47xa=_0x2393[15]}else {_0xcf47x9= _0x2393[16]+ _0xcf47x4,_0xcf47xa= _0x2393[17]};return _0xcf47x8[_0x2393[19]](_0x2393[18],0),_0xcf47x8[_0x2393[19]](_0x2393[20],_0x2393[17]),_0x2393[9]== _0xcf47x7[_0x2393[21]]?(_0xcf47x8[_0x2393[19]](_0x2393[22],_0x2393[23]+ _0xcf47x7[_0x2393[24]]+ _0xcf47xa),_0xcf47x8[_0x2393[19]](_0x2393[25],_0x2393[26])):_0x2393[10]== _0xcf47x7[_0x2393[21]]?(_0xcf47x8[_0x2393[19]](_0x2393[22],_0x2393[27]+ _0xcf47x7[_0x2393[24]]+ _0xcf47xa+ _0xcf47x9),_0xcf47x3?_0xcf47x8[_0x2393[19]](_0x2393[25],_0x2393[28]):_0xcf47x8[_0x2393[19]](_0x2393[25],_0x2393[29])):_0x2393[11]== _0xcf47x7[_0x2393[21]]&& (_0xcf47x8[_0x2393[19]](_0x2393[22],_0x2393[30]+ _0xcf47x7[_0x2393[24]]+ _0xcf47xa),_0xcf47x3&& _0xcf47x8[_0x2393[19]](_0x2393[25],_0x2393[1])),_0xcf47x8}function _0xcf47x7(){$(_0x2393[32])[_0x2393[31]](_0xcf47x5),$(_0x2393[34])[_0x2393[33]](),$(_0x2393[36])[_0x2393[35]]()}$(_0x2393[41])[_0x2393[40]](_0x2393[39])[_0x2393[38]](_0x2393[37]),$(_0x2393[43])[_0x2393[40]](_0x2393[42])[_0x2393[38]](_0x2393[37]),$(_0x2393[52])[_0x2393[51]](_0x2393[44],function(){var _0xcf47x2=_0xcf47x6($(this)[_0x2393[47]](_0x2393[46])[_0x2393[19]](_0x2393[45]),560,315);$(_0x2393[49])[_0x2393[48]](_0xcf47x2),setTimeout(function(){$(_0x2393[34])[_0x2393[50]]()},300),$(_0x2393[32])[_0x2393[38]](_0xcf47x5)}),$(_0x2393[34])[_0x2393[44]](function(){_0xcf47x7()}),$(document)[_0x2393[54]](function(_0xcf47x2){27=== _0xcf47x2[_0x2393[53]]&& _0xcf47x7()})}ProductVideo() {% endif %} }; /* end-dbtfy-product-video */';

                // add js register
                $theme_js_content = $shop->api()->request(
                    'GET',
                    '/admin/api/themes/'.$theme->shopify_theme_id.'/assets.json',
                    ['asset' => ['key' => 'assets/dbtfy-addons.js.liquid'] ]
                )['body']['asset']['value'] ?? '';

                if( ( $pos = strpos( $theme_js_content , "/* start-register-product-video */" ) ) === false ) {
                        $new_theme_js = str_replace('var sections = new theme.Sections();','var sections = new theme.Sections();/* start-register-product-video */sections.register("product-template", themeProductVideo);/* end-register-product-video */', $theme_js_content);

                    $add_js = $shop->api()->request(
                        'PUT',
                        '/admin/api/themes/'.$theme->shopify_theme_id.'/assets.json',
                        ['asset' => ['key' => 'assets/dbtfy-addons.js.liquid', 'value' => $new_theme_js] ]
                    );
                }

                $theme_js_content = $shop->api()->request(
                    'GET',
                    '/admin/api/themes/'.$theme->shopify_theme_id.'/assets.json',
                    ['asset' => ['key' => 'assets/dbtfy-addons.js.liquid'] ]
                )['body']['asset']['value'] ?? '';
                $replace_code= '/* start-dbtfy-addons */';
                if( ( $pos = strpos( $theme_js_content , '/* start-dbtfy-product-video */' ) ) === false ) {
                        $new_theme_js = str_replace($replace_code, $replace_code.$script, $theme_js_content);

                    $add_js = $shop->api()->request(
                        'PUT',
                        '/admin/api/themes/'.$theme->shopify_theme_id.'/assets.json',
                        ['asset' => ['key' => 'assets/dbtfy-addons.js.liquid', 'value' => $new_theme_js] ]
                    );
                }
            }catch(\GuzzleHttp\Exception\ClientException $e){
                logger('update js on cookie_box addon throws client exception');
            }
            catch(\Exception $e){
                logger('update js on cookie_box addon throws exception');
            }

            // add scss
            try{
                $styles = (string) '/* start-dbtfy-product-video */{% if settings.dbtfy_product_video %}.dbtfy-product_video{#ProductVideo{position:fixed;left:0;top:0;width:100%;height:100%;z-index:$zindexDrawer;@include display-flexbox();@include justify-content(center);@include align-items(center)}}.video-thumbnail{&:before{@include transition($transitions);@include fontAwesome;content:"\f144";position:absolute;z-index:1;opacity:$opacity-link-hover}&.product-single__photo-wrapper{&:before{@include display-flexbox();@include justify-content(center);@include align-items(center);top:0;left:0;width:100%;height:100%;cursor:pointer;font-size:$bigFontSize;line-height:1}&:hover{&:before{@include transform(scale(1.5));color:$colorSecondary;opacity:1}}}&.product-single__thumbnail{position:relative;.slick-current &,&.active-thumb{&:before{color:$colorSecondary;opacity:1}}&:before{top:$gutter-sm/2;left:$gutter-sm/2;@include screen($small){font-size:$baseFontSize-sm;top:$spacer-xs;left:$spacer-xs}}&:hover{&:before{color:$colorSecondary;opacity:1}}}}{% endif %}/* end-dbtfy-product-video */';

                $theme_style_content = $shop->api()->request(
                    'GET',
                    '/admin/api/themes/'.$theme->shopify_theme_id.'/assets.json',
                    ['asset' => ['key' => 'assets/theme.scss.liquid'] ]
                )['body']['asset']['value'] ?? '';

                if( ( $pos = strpos( $theme_style_content , 'start-dbtfy-product-video' ) ) === false ) {
                    $new_theme_styles = str_replace($theme_style_content, $theme_style_content.$styles, $theme_style_content);
                    $add_styles = $shop->api()->request(
                        'PUT',
                        '/admin/api/themes/'.$theme->shopify_theme_id.'/assets.json',
                        ['asset' => ['key' => 'assets/theme.scss.liquid', 'value' => $new_theme_styles] ]
                    );
                }
            }
            catch(\GuzzleHttp\Exception\ClientException $e){
                logger('update CSS on product_video addon throws client exception');
            }
            catch(\Exception $e){
                logger('update CSS on product_video addon throws exception');
            }

            // Update product template
            try{
                $product_template = $shop->api()->request(
                    'GET',
                    '/admin/api/themes/'.$theme->shopify_theme_id.'/assets.json',
                    ['asset' => ['key' => 'snippets/product-template.liquid'] ]
                )['body']['asset']['value'] ?? '';

                if( ( $pos = strpos( $product_template , 'dbtfy-product-video' ) ) === false ) {

                    if( ( $pos = strrpos( $product_template , '<!-- product details -->' ) ) !== false ) {
                        $new_prod_template = preg_replace('/<\/div>\s+<!-- product details -->/', '{% include "dbtfy-product-video" %}</div>

          <!-- product details -->', $product_template);
                        $update_prod_template = $shop->api()->request(
                            'PUT',
                            '/admin/api/themes/'.$theme->shopify_theme_id.'/assets.json',
                            ['asset' => ['key' => 'snippets/product-template.liquid', 'value' => $new_prod_template] ]
                        );
                    }
                }
            }
            catch(\GuzzleHttp\Exception\ClientException $e){
                logger('update dbtfy-product-video on trustbadge addon throws client exception');
            }
            catch(\Exception $e){
                logger('update dbtfy-product-video on trustbadge addon throws exception');
            }

        }
    }
}

// deactivate
if (! function_exists('deactivate_product_video_addon')) {
    function deactivate_product_video_addon($StoreThemes, $shop, $checkaddon) {
        foreach ($StoreThemes as $theme) {

            // remove schema
            $schema_get = $shop->api()->request(
                'GET',
                '/admin/api/themes/'.$theme->shopify_theme_id.'/assets.json',
                ['asset' => ['key' => 'config/settings_schema.json'] ]
            )['body'];

            if(!isset($schema_get['asset']['value']))
            {
                deactivate_product_video_addon_curl($theme, $shop);
                continue;
            }
            else
            {
                $schema = $schema_get['asset']['value'] ?? '';
            }

            $json = json_decode($schema, true);
            $json = array_filter($json, function ($obj) {
              if (stripos($obj['name'], 'Product video') !== false) {
                  return false;
              }
              return true;
            });

            if(str_contains($schema,'Product video')){
                $value = json_encode(array_values($json));
                $updated_schema = $value;
                $update_schema_settings = $shop->api()->request(
                    'PUT',
                    '/admin/api/themes/'.$theme->shopify_theme_id.'/assets.json',
                    ['asset' => ['key' => 'config/settings_schema.json', 'value' => $updated_schema] ]
                );
            }

            // remove scss
            $theme_style_content = $shop->api()->request(
                'GET',
                '/admin/api/themes/'.$theme->shopify_theme_id.'/assets.json',
                ['asset' => ['key' => 'assets/theme.scss.liquid'] ]
            )['body']['asset']['value'] ?? '';

            $trustbadge_Style = (string) '/* start-dbtfy-product-video */';
            $end = (string) '/* end-dbtfy-product-video */';
            $string = ' ' . $theme_style_content;
            $ini = strpos($string, $trustbadge_Style);

            if ($ini == 0) {
              $parsed = '';
            }else{
              $ini += strlen($trustbadge_Style);
              $len = strpos($string, $end, $ini) - $ini;
              $parsed = substr($string, $ini, $len);
            }
            $values = $trustbadge_Style.''.$parsed.''.$end;

            if(str_contains($theme_style_content,'.dbtfy-product_video')){
                $value = str_replace($values, " ", $theme_style_content);
                $new_theme_styles = (string) $value;

                $update_styles = $shop->api()->request(
                    'PUT',
                    '/admin/api/themes/'.$theme->shopify_theme_id.'/assets.json',
                    ['asset' => ['key' => 'assets/theme.scss.liquid', 'value' => $new_theme_styles] ]
                );
            }

            // remove snippet
            $delete_trustbadge_snippet = $shop->api()->request(
                'DELETE',
                '/admin/api/themes/'.$theme->shopify_theme_id.'/assets.json',
                ['asset' => ['key' => 'snippets/dbtfy-product-video.liquid'] ]
            );

            // remove include
            $product_template = $shop->api()->request(
                'GET',
                '/admin/api/themes/'.$theme->shopify_theme_id.'/assets.json',
                ['asset' => ['key' => 'snippets/product-template.liquid'] ]
            )['body']['asset']['value'] ?? '';

            if(str_contains($product_template,'dbtfy-product-video')){
                $value  =  explode('{% include "dbtfy-product-video" %}',$product_template,2);

                if(isset($value[0]) && isset($value[1])){
                    $value = $value[0].' '.$value[1];
                }
                else{
                    $value = (string) $product_template;
                }

                $new_prod_template = (string) $value;
                $update_prod_template = $shop->api()->request(
                    'PUT',
                    '/admin/api/themes/'.$theme->shopify_theme_id.'/assets.json',
                    ['asset' => ['key' => 'snippets/product-template.liquid', 'value' => $new_prod_template] ]
                );
            }

            // remove js addon
            try{
               $theme_js_content = $shop->api()->request(
                    'GET',
                    '/admin/api/themes/'.$theme->shopify_theme_id.'/assets.json',
                    ['asset' => ['key' => 'assets/dbtfy-addons.js.liquid'] ]
                )['body']['asset']['value'] ?? '';

                $trustbadge_js = (string) '/* start-dbtfy-product-video */';
                $end_js = (string) '/* end-dbtfy-product-video */';
                $string_js = ' ' . $theme_js_content;
                $ini_js = strpos($string_js, $trustbadge_js);
                if ($ini_js == 0) {
                    $parsed_js = '';
                } else{
                    $ini_js += strlen($trustbadge_js);
                    $len_js = strpos($string_js, $end_js, $ini_js) - $ini_js;
                    $parsed_js = substr($string_js, $ini_js, $len_js);
                }
                $value_js = $trustbadge_js.''.$parsed_js.''.$end_js;
                if(!empty($theme_js_content) && str_contains($theme_js_content,'/* start-dbtfy-product-video */')){
                    $value = str_replace($value_js, " ", $theme_js_content);
                    $new_theme_js = (string) $value;
                    if(str_contains($new_theme_js,'/* start-register-product-video */')){
                        $trustbadge_js1 = (string) '/* start-register-product-video */';
                        $end_js = (string) '/* end-register-product-video */';
                        $string_js = ' ' . $new_theme_js;
                        $ini_js = strpos($string_js, $trustbadge_js1);
                        if ($ini_js == 0) {
                            $parsed_js = '';
                        } else{
                            $ini_js += strlen($trustbadge_js1);
                            $len_js = strpos($string_js, $end_js, $ini_js) - $ini_js;
                            $parsed_js = substr($string_js, $ini_js, $len_js);
                        }
                        $value_js = $trustbadge_js1.''.$parsed_js.''.$end_js;

                        $value = str_replace($value_js, " ", $new_theme_js);
                        $new_theme_js1 = (string) $value;
                        $update_js = $shop->api()->request(
                            'PUT',
                            '/admin/api/themes/'.$theme->shopify_theme_id.'/assets.json',
                            ['asset' => ['key' => 'assets/dbtfy-addons.js.liquid', 'value' => $new_theme_js1] ]
                        );
                    }
                    else{
                        $update_js = $shop->api()->request(
                            'PUT',
                            '/admin/api/themes/'.$theme->shopify_theme_id.'/assets.json',
                            ['asset' => ['key' => 'assets/dbtfy-addons.js.liquid', 'value' => $new_theme_js] ]
                        );
                    }
                }
            }
            catch(\GuzzleHttp\Exception\ClientException $e){
                logger('add product_video throws client exception');
            }
            catch(\Exception $e){
                logger('add product_video throws exception');
            }
        }
    }
}


if (! function_exists('deactivate_product_video_addon_curl')) {
    function deactivate_product_video_addon_curl($theme, $shop) {

        // remove schema
        $schema = getThemeFileCurl($shop, $theme, 'config/settings_schema.json');

        $json = json_decode($schema, true);
        $json = array_filter($json, function ($obj) {
          if (stripos($obj['name'], 'Product video') !== false) {
              return false;
          }
          return true;
        });

        if(str_contains($schema,'Product video')){
            $value = json_encode(array_values($json));
            $updated_schema = $value;
            $update_schema_settings = putThemeFileCurl($shop, $theme, $updated_schema, 'config/settings_schema.json');
        }

        // remove scss
        $theme_style_content = getThemeFileCurl($shop, $theme, 'assets/theme.scss.liquid') ?? '';

        $trustbadge_Style = (string) '/* start-dbtfy-product-video */';
        $end = (string) '/* end-dbtfy-product-video */';
        $string = ' ' . $theme_style_content;
        $ini = strpos($string, $trustbadge_Style);

        if ($ini == 0) {
          $parsed = '';
        }else{
          $ini += strlen($trustbadge_Style);
          $len = strpos($string, $end, $ini) - $ini;
          $parsed = substr($string, $ini, $len);
        }
        $values = $trustbadge_Style.''.$parsed.''.$end;

        if(str_contains($theme_style_content,'.dbtfy-product_video')){
            $value = str_replace($values, " ", $theme_style_content);
            $new_theme_styles = (string) $value;

            $update_styles = putThemeFileCurl($shop, $theme, $new_theme_styles, 'assets/theme.scss.liquid');
        }

        // remove snippet
        $delete_trustbadge_snippet = deleteThemeFilesCurl($shop, $theme, 'snippets/dbtfy-product-video.liquid');

        // remove include
        $product_template = getThemeFileCurl($shop, $theme, 'snippets/product-template.liquid');

        if(str_contains($product_template,'dbtfy-product-video')){
            $value  =  explode('{% include "dbtfy-product-video" %}',$product_template,2);

            if(isset($value[0]) && isset($value[1])){
                $value = $value[0].' '.$value[1];
            }
            else{
                $value = (string) $product_template;
            }

            $new_prod_template = (string) $value;
            $update_prod_template = putThemeFileCurl($shop, $theme, $new_prod_template, 'snippets/product-template.liquid');
        }

        // remove js addon
        try{
           $theme_js_content = getThemeFileCurl($shop, $theme, 'assets/dbtfy-addons.js.liquid') ?? '';
            if ($theme_js_content == null)
            {
                $theme_js_content = '';
            }
            $trustbadge_js = (string) '/* start-dbtfy-product-video */';
            $end_js = (string) '/* end-dbtfy-product-video */';
            $string_js = ' ' . $theme_js_content;
            $ini_js = strpos($string_js, $trustbadge_js);
            if ($ini_js == 0) {
                $parsed_js = '';
            } else{
                $ini_js += strlen($trustbadge_js);
                $len_js = strpos($string_js, $end_js, $ini_js) - $ini_js;
                $parsed_js = substr($string_js, $ini_js, $len_js);
            }
            $value_js = $trustbadge_js.''.$parsed_js.''.$end_js;
            if(!empty($theme_js_content) && str_contains($theme_js_content,'/* start-dbtfy-product-video */')){
                $value = str_replace($value_js, " ", $theme_js_content);
                $new_theme_js = (string) $value;
                if(str_contains($new_theme_js,'/* start-register-product-video */')){
                    $trustbadge_js1 = (string) '/* start-register-product-video */';
                    $end_js = (string) '/* end-register-product-video */';
                    $string_js = ' ' . $new_theme_js;
                    $ini_js = strpos($string_js, $trustbadge_js1);
                    if ($ini_js == 0) {
                        $parsed_js = '';
                    } else{
                        $ini_js += strlen($trustbadge_js1);
                        $len_js = strpos($string_js, $end_js, $ini_js) - $ini_js;
                        $parsed_js = substr($string_js, $ini_js, $len_js);
                    }
                    $value_js = $trustbadge_js1.''.$parsed_js.''.$end_js;

                    $value = str_replace($value_js, " ", $new_theme_js);
                    $new_theme_js1 = (string) $value;
                    $update_js = putThemeFileCurl($shop, $theme, $new_theme_js1, 'assets/dbtfy-addons.js.liquid');
                }
                else{
                    $update_js = putThemeFileCurl($shop, $theme, $new_theme_js, 'assets/dbtfy-addons.js.liquid');
                }
            }
        }
        catch(\GuzzleHttp\Exception\ClientException $e){
            logger('add product_video throws client exception');
        }
        catch(\Exception $e){
            logger('add product_video throws exception');
        }
    }
}
?>
