<?php
//activate
if (! function_exists('activate_smart_search_addon')) {
    function activate_smart_search_addon($StoreThemes, $shop) {
      	foreach ($StoreThemes as $theme) {

            // add schema
            try{
                $schema = $shop->api()->request(
                    'GET',
                    '/admin/api/themes/'.$theme->shopify_theme_id.'/assets.json',
                    ['asset' => ['key' => 'config/settings_schema.json'] ]
                )['body']['asset']['value'] ?? '';

                $addon_schema = (string) '
  {
    "name": "Smart search",
    "settings": [
      {
        "type": "header",
        "content": "Activation"
      },
      {
        "type": "checkbox",
        "id": "dbtfy_smart_search",
        "label": "Activate",
        "info": "To show collections, articles and pages, uncheck the \"Only search products\" checkbox in the Cart\/Search theme settings",
        "default": false
      },
      {
        "type": "header",
        "content": "Result settings"
      },
      {
        "type": "checkbox",
        "id": "dbtfy_smart_search_price",
        "label": "Show price",
        "default": true
      },
      {
        "type": "checkbox",
        "id": "dbtfy_smart_search_vendor",
        "label": "Show vendor",
        "default": false
      },
      {
        "type": "range",
        "id": "dbtfy_smart_search_limit",
        "label": "Result limit",
        "min": 2,
        "max": 10,
        "step": 1,
        "default": 4
      },
      {
        "type": "header",
        "content": "Text settings"
      },
      {
        "type": "text",
        "id": "dbtfy_smart_search_products",
        "label": "Products",
        "default": "Products"
      },
      {
        "type": "text",
        "id": "dbtfy_smart_search_collections",
        "label": "Collections",
        "default": "Collections"
      },
      {
        "type": "text",
        "id": "dbtfy_smart_search_articles",
        "label": "Articles",
        "default": "Articles"
      },
      {
        "type": "text",
        "id": "dbtfy_smart_search_pages",
        "label": "Pages",
        "default": "Pages"
      },
      {
        "type": "text",
        "id": "dbtfy_smart_search_all",
        "label": "Show all result",
        "default": "Show all results for"
      }
    ]
  }';

                if( ( $badgePos = strpos( $schema , 'dbtfy_smart_search' ) ) === false ) {
                    if( ( $pos = strrpos( $schema , ']' ) ) !== false ) {
                        $updated_schema    = substr_replace( $schema , ",".$addon_schema."]" , $pos );
                        $update_schema_settings = $shop->api()->request(
                            'PUT',
                            '/admin/api/themes/'.$theme->shopify_theme_id.'/assets.json',
                            ['asset' => ['key' => 'config/settings_schema.json', 'value' => $updated_schema] ]
                        );
                    }
                }
            }
            catch(\GuzzleHttp\Exception\ClientException $e){
                logger('update schema on smart search addon throws client exception');
            }
            catch(\Exception $e){
                logger('update schema on smart search addon throws exception');
            }

            // add snippet
            try{
                $addon_snippet = (string) '{%- comment -%}Please do not edit this file. Any modification can be lost as it is automatically updated by Debutify{%- endcomment -%}
{%- if settings.dbtfy_smart_search -%}
<div class="dbtfy dbtfy-smart_search"
     data-limit="{{ settings.dbtfy_smart_search_limit }}"
     data-price="{{ settings.dbtfy_smart_search_price }}"
     data-vendor="{{ settings.dbtfy_smart_search_vendor }}">
  <div id="SmartSearch">
    <div class="ss_section_title ss_loading" style="display: none;">
      <span class="fas fa-spinner fa-spin ss_spin_icon"></span>
    </div>

    <div class="ss_section_wrapper" style="display: none;">
      <div class="ss_section ss_products" style="display: none;">
        <div class="ss_section_title">
          {{ settings.dbtfy_smart_search_products }}
        </div>
        <div class="ss_content"></div>
      </div>
      {% unless settings.search_product %}
      <div class="ss_section ss_collections" style="display: none;">
        <div class="ss_section_title">
          {{ settings.dbtfy_smart_search_collections }}
        </div>
        <div class="ss_content"></div>
      </div>
      <div class="ss_section ss_posts" style="display: none;">
        <div class="ss_section_title">
          {{ settings.dbtfy_smart_search_articles }}
        </div>
        <div class="ss_content"></div>
      </div>
      <div class="ss_section ss_pages" style="display: none;">
        <div class="ss_section_title">
          {{ settings.dbtfy_smart_search_pages }}
        </div>
        <div class="ss_content"></div>
      </div>
      {% endunless %}

      <div class="ss_showall">
        <a href="" class="btn btn--banner">{{ settings.dbtfy_smart_search_all}} "<span></span>" <i class="fas fa-arrow-right"></i></a>
      </div>
    </div>

  </div>
</div>
{%- endif -%}';
                $addon_snippet = addScriptTagCondition($shop, '{%- comment -%}Please do not edit this file. Any modification can be lost as it is automatically updated by Debutify{%- endcomment -%}', $addon_snippet);
               $create_addon_snippet = $shop->api()->request(
                            'PUT',
                    '/admin/api/themes/'.$theme->shopify_theme_id.'/assets.json',
                    ['asset' => ['key' => 'snippets/dbtfy-smart-search.liquid', 'value' => $addon_snippet] ]
                );
            }
            catch(\GuzzleHttp\Exception\ClientException $e){
                logger('add smart-search throws client exception');
            }
            catch(\Exception $e){
                logger('add smart-search throws exception');
            }

            // add scss
            try{
                $styles = (string) '/* start-dbtfy-smart-search */{% if settings.dbtfy_smart_search %}$smartSearchHeight:$heightInput + $gutter*2;.dbtfy-smart_search{#SmartSearch{position:absolute;left:0;top:$smartSearchHeight;background-color:$colorDrawer;width:100%;overflow-y:auto;max-height:calc(100vh - #{$smartSearchHeight});@include shadow(inset $shadowBottom)}.ss_loading{text-align:center;.ss_spin_icon{font-size:$baseFontSize-lg;color:$colorDrawerPrimary}}.ss_section_title{border:$borders;border-color:$colorDrawerDefault;background-color:$colorDrawerDefault;padding:$gutter-sm;@include accentFontStack}.ss_item{@include animated(fadeInUp);animation-duration:$transitionDuration;&:nth-child(2){animation-delay:.1s}&:nth-child(3){animation-delay:.2s}&:nth-child(4){animation-delay:.3s}&:nth-child(5){animation-delay:.4s}&:nth-child(6){animation-delay:.5s}&:nth-child(7){animation-delay:.6s}&:nth-child(8){animation-delay:.7s}&:nth-child(9){animation-delay:.8s}&:nth-child(10){animation-delay:.9s}&:not(:last-child){a{padding-bottom:0}}&.item-selected{a{opacity:$opacity-link-hover;&:after{opacity:1}}}a{padding:$gutter-sm;@include display-flexbox();@include align-items(center);&:after{@include fontAwesome;content:"\f002";opacity:0;margin-left:auto;padding-left:$spacer-sm;color:$colorDrawerPrimary;@include transition($transitions)}&:hover{&:after{opacity:1}}}}.ss_thumbnail{padding-right:$spacer;img{height:60px;max-width:60px;width:100%;display:block;object-fit:cover}}.ss_info{@include autoSpacer($spacer-xs);&>*{display:block}.ss_title{@include headerFontStack}.ss_price{@include accentFontStack;font-size:$baseFontSize-sm;line-height:1;.price-compare{padding-right:$spacer-xs}}.ss_vendor{font-size:$baseFontSize-sm;line-height:1}}}#SearchDrawer{overflow-y:initial;overflow-x:initial;.drawer__inner{overflow:initial}}{% endif %}/* end-dbtfy-smart-search */';

                $theme_style_content = $shop->api()->request(
                    'GET',
                    '/admin/api/themes/'.$theme->shopify_theme_id.'/assets.json',
                    ['asset' => ['key' => 'assets/theme.scss.liquid'] ]
                )['body']['asset']['value'] ?? '';

                if( ( $pos = strpos( $theme_style_content , 'start-dbtfy-smart-search' ) ) === false ) {
                    $new_theme_styles = str_replace($theme_style_content, $theme_style_content.$styles, $theme_style_content);

                    $add_styles = $shop->api()->request(
                        'PUT',
                        '/admin/api/themes/'.$theme->shopify_theme_id.'/assets.json',
                        ['asset' => ['key' => 'assets/theme.scss.liquid', 'value' => $new_theme_styles] ]
                    );
                }
            }
            catch(\GuzzleHttp\Exception\ClientException $e){
                logger('update CSS on smart-search addon throws client exception');
            }
            catch(\Exception $e){
                logger('update CSS on smart-search addon throws exception');
            }

            // add include
            try{
                $product_template = $shop->api()->request(
                    'GET',
                    '/admin/api/themes/'.$theme->shopify_theme_id.'/assets.json',
                    ['asset' => ['key' => 'layout/theme.liquid'] ]
                )['body']['asset']['value'] ?? '';

                if( ( $pos = strpos( $product_template , 'dbtfy-smart-search' ) ) === false ) {
                    if( ( $pos = strrpos( $product_template , '<div id="SearchDrawer" class="drawer drawer--top">' ) ) !== false ) {
                        $new_prod_template = str_replace('<div id="SearchDrawer" class="drawer drawer--top">', '<div id="SearchDrawer" class="drawer drawer--top">{% include "dbtfy-smart-search" %}', $product_template);
                        $update_prod_template = $shop->api()->request(
                            'PUT',
                            '/admin/api/themes/'.$theme->shopify_theme_id.'/assets.json',
                            ['asset' => ['key' => 'layout/theme.liquid', 'value' => $new_prod_template] ]
                        );
                    }
                }
            }
            catch(\GuzzleHttp\Exception\ClientException $e){
                logger('update smart-search include throws client exception');
            }
            catch(\Exception $e){
                logger('update smart-search include throws exception');
            }

            // add js addon
            try{
              $script= (string)'/* start-dbtfy-smart-search */function themeSmartSearch() { {% if settings.dbtfy_smart_search %} var _0x9ce8=["\x2E\x64\x62\x74\x66\x79\x2D\x73\x6D\x61\x72\x74\x5F\x73\x65\x61\x72\x63\x68","\x70\x72\x69\x63\x65","\x64\x61\x74\x61","\x76\x65\x6E\x64\x6F\x72","\x69\x6E\x70\x75\x74\x5B\x6E\x61\x6D\x65\x3D\x22\x71\x22\x5D","\x66\x69\x6E\x64","\x23\x53\x65\x61\x72\x63\x68\x44\x72\x61\x77\x65\x72\x20\x66\x6F\x72\x6D\x5B\x61\x63\x74\x69\x6F\x6E\x3D\x22\x2F\x73\x65\x61\x72\x63\x68\x22\x5D","\x2E\x73\x73\x5F\x6C\x6F\x61\x64\x69\x6E\x67","\x2E\x73\x73\x5F\x73\x65\x63\x74\x69\x6F\x6E","\x2E\x73\x73\x5F\x73\x65\x63\x74\x69\x6F\x6E\x5F\x77\x72\x61\x70\x70\x65\x72","\x23\x53\x65\x61\x72\x63\x68\x44\x72\x61\x77\x65\x72\x20\x2E\x73\x65\x61\x72\x63\x68\x2D\x69\x6E\x70\x75\x74","\x76\x61\x6C","\x66\x6F\x72\x6D","\x63\x6C\x6F\x73\x65\x73\x74","\x2F\x73\x65\x61\x72\x63\x68\x3F\x71\x3D","\x6C\x69\x6D\x69\x74","\x77\x68\x69\x63\x68","\x70\x72\x65\x76\x65\x6E\x74\x44\x65\x66\x61\x75\x6C\x74","\x73\x68\x6F\x77","\x68\x69\x64\x65","\x70\x72\x6F\x64\x75\x63\x74\x73","\x72\x65\x73\x75\x6C\x74\x73","\x72\x65\x73\x6F\x75\x72\x63\x65\x73","\x61\x72\x74\x69\x63\x6C\x65\x73","\x70\x61\x67\x65\x73","\x63\x6F\x6C\x6C\x65\x63\x74\x69\x6F\x6E\x73","\x6C\x65\x6E\x67\x74\x68","\x2E\x73\x73\x5F\x70\x72\x6F\x64\x75\x63\x74\x73","\x65\x6D\x70\x74\x79","\x2E\x73\x73\x5F\x63\x6F\x6E\x74\x65\x6E\x74","\x2F\x70\x72\x6F\x64\x75\x63\x74\x73\x2F","\x68\x61\x6E\x64\x6C\x65","\x6D\x6F\x6E\x65\x79\x46\x6F\x72\x6D\x61\x74","\x73\x74\x72\x69\x6E\x67\x73","\x63\x6F\x6D\x70\x61\x72\x65\x5F\x61\x74\x5F\x70\x72\x69\x63\x65","\x76\x61\x72\x69\x61\x6E\x74\x73","\x70\x72\x6F\x64\x75\x63\x74","\x68\x72\x65\x66","\x61\x74\x74\x72","\x3C\x61\x3E\x3C\x2F\x61\x3E","\x73\x72\x63","\x69\x6D\x61\x67\x65","\x68\x74\x74\x70\x3A","","\x72\x65\x70\x6C\x61\x63\x65","\x5F\x31\x30\x30\x78\x24\x31","\x3C\x73\x70\x61\x6E\x20\x63\x6C\x61\x73\x73\x3D\x22\x73\x73\x5F\x74\x68\x75\x6D\x62\x6E\x61\x69\x6C\x22\x3E\x3C\x69\x6D\x67\x20\x73\x72\x63\x3D\x22","\x22\x20\x2F\x3E\x3C\x2F\x73\x70\x61\x6E\x3E","\x61\x70\x70\x65\x6E\x64","\x3C\x73\x70\x61\x6E\x20\x63\x6C\x61\x73\x73\x3D\x22\x73\x73\x5F\x69\x6E\x66\x6F\x22\x3E\x3C\x73\x70\x61\x6E\x20\x63\x6C\x61\x73\x73\x3D\x22\x73\x73\x5F\x74\x69\x74\x6C\x65\x22\x3E","\x74\x69\x74\x6C\x65","\x3C\x2F\x73\x70\x61\x6E\x3E","\x3C\x73\x70\x61\x6E\x20\x63\x6C\x61\x73\x73\x3D\x22\x73\x73\x5F\x70\x72\x69\x63\x65\x22\x3E\x3C\x73\x70\x61\x6E\x20\x63\x6C\x61\x73\x73\x3D\x22\x70\x72\x69\x63\x65\x2D\x63\x6F\x6D\x70\x61\x72\x65\x22\x3E","\x66\x6F\x72\x6D\x61\x74\x4D\x6F\x6E\x65\x79","\x43\x75\x72\x72\x65\x6E\x63\x79","\x3C\x2F\x73\x70\x61\x6E\x3E\x3C\x73\x70\x61\x6E\x20\x63\x6C\x61\x73\x73\x3D\x22\x6F\x6E\x2D\x73\x61\x6C\x65\x22\x3E","\x3C\x2F\x73\x70\x61\x6E\x3E\x3C\x2F\x73\x70\x61\x6E\x3E","\x3C\x73\x70\x61\x6E\x20\x63\x6C\x61\x73\x73\x3D\x22\x73\x73\x5F\x70\x72\x69\x63\x65\x22\x3E\x3C\x73\x70\x61\x6E\x3E","\x3C\x73\x70\x61\x6E\x20\x63\x6C\x61\x73\x73\x3D\x22\x73\x73\x5F\x76\x65\x6E\x64\x6F\x72\x22\x3E","\x3C\x64\x69\x76\x20\x63\x6C\x61\x73\x73\x3D\x22\x73\x73\x5F\x69\x74\x65\x6D\x22\x3E\x3C\x2F\x64\x69\x76\x3E","\x77\x72\x61\x70","\x70\x61\x72\x65\x6E\x74","\x67\x65\x74\x4A\x53\x4F\x4E","\x65\x61\x63\x68","\x2E\x73\x73\x5F\x70\x6F\x73\x74\x73","\x75\x72\x6C","\x2E\x73\x73\x5F\x70\x61\x67\x65\x73","\x2E\x73\x73\x5F\x63\x6F\x6C\x6C\x65\x63\x74\x69\x6F\x6E\x73","\x66\x65\x61\x74\x75\x72\x65\x64\x5F\x69\x6D\x61\x67\x65","\x61","\x2E\x73\x73\x5F\x73\x68\x6F\x77\x61\x6C\x6C","\x74\x65\x78\x74","\x73\x70\x61\x6E","\x64\x6F\x6E\x65","\x2F\x73\x65\x61\x72\x63\x68\x2F\x73\x75\x67\x67\x65\x73\x74\x2E\x6A\x73\x6F\x6E","\x70\x72\x6F\x64\x75\x63\x74\x2C\x61\x72\x74\x69\x63\x6C\x65\x2C\x70\x61\x67\x65\x2C\x63\x6F\x6C\x6C\x65\x63\x74\x69\x6F\x6E","\x6C\x61\x73\x74","\x6B\x65\x79\x75\x70","\x61\x75\x74\x6F\x63\x6F\x6D\x70\x6C\x65\x74\x65","\x6F\x66\x66","\x6B\x65\x79\x64\x6F\x77\x6E","\x6B\x65\x79\x43\x6F\x64\x65","\x2E\x69\x74\x65\x6D\x2D\x73\x65\x6C\x65\x63\x74\x65\x64","\x6E\x65\x78\x74","\x69\x74\x65\x6D\x2D\x73\x65\x6C\x65\x63\x74\x65\x64","\x72\x65\x6D\x6F\x76\x65\x43\x6C\x61\x73\x73","\x61\x64\x64\x43\x6C\x61\x73\x73","\x65\x71","\x2E\x73\x73\x5F\x69\x74\x65\x6D","\x70\x72\x65\x76","\x2E\x69\x74\x65\x6D\x2D\x73\x65\x6C\x65\x63\x74\x65\x64\x20\x61","\x6C\x6F\x63\x61\x74\x69\x6F\x6E","\x73\x75\x62\x6D\x69\x74","\x74\x61\x72\x67\x65\x74","\x63\x6C\x6F\x73\x65","\x6F\x6E"];function SmartSearch(){var _0xc1f9x2,_0xc1f9x3=$(_0x9ce8[0]),_0xc1f9x4=_0xc1f9x3[_0x9ce8[2]](_0x9ce8[1]),_0xc1f9x5=_0xc1f9x3[_0x9ce8[2]](_0x9ce8[3]),_0xc1f9x6=($(_0x9ce8[6])[_0x9ce8[5]](_0x9ce8[4]),$(_0x9ce8[7])),_0xc1f9x7=($(_0x9ce8[8]),$(_0x9ce8[9])),_0xc1f9x8=$(_0x9ce8[10]);_0xc1f9x8[_0x9ce8[38]](_0x9ce8[78],_0x9ce8[79])[_0x9ce8[77]](function(_0xc1f9x8){var _0xc1f9x9=$(this),_0xc1f9xa=_0xc1f9x9[_0x9ce8[11]](),_0xc1f9xb=(_0xc1f9x9[_0x9ce8[13]](_0x9ce8[12]),_0x9ce8[14]+ _0xc1f9xa),_0xc1f9xc=_0xc1f9x3[_0x9ce8[2]](_0x9ce8[15]);if(38=== _0xc1f9x8[_0x9ce8[16]]|| 40=== _0xc1f9x8[_0x9ce8[16]]|| 13=== _0xc1f9x8[_0x9ce8[16]]|| 17=== _0xc1f9x8[_0x9ce8[16]]){return _0xc1f9x8[_0x9ce8[17]](),!1};if(_0xc1f9x6[_0x9ce8[18]](),_0xc1f9x7[_0x9ce8[19]](),clearTimeout(_0xc1f9x2),!_0xc1f9xa){return _0xc1f9x6[_0x9ce8[19]](),_0xc1f9x7[_0x9ce8[19]](),!1};_0xc1f9x2= setTimeout(function(){jQuery[_0x9ce8[62]](_0x9ce8[74],{q:_0xc1f9xa,resources:{type:_0x9ce8[75],limit:_0xc1f9xc,options:{unavailable_products:_0x9ce8[76],fields:_0x9ce8[50]}}})[_0x9ce8[73]](function(_0xc1f9x8){var _0xc1f9x9=_0xc1f9x8[_0x9ce8[22]][_0x9ce8[21]][_0x9ce8[20]],_0xc1f9xc=_0xc1f9x8[_0x9ce8[22]][_0x9ce8[21]][_0x9ce8[23]],_0xc1f9x2=_0xc1f9x8[_0x9ce8[22]][_0x9ce8[21]][_0x9ce8[24]],_0xc1f9x3=_0xc1f9x8[_0x9ce8[22]][_0x9ce8[21]][_0x9ce8[25]];0== _0xc1f9x9[_0x9ce8[26]]?$(_0x9ce8[27])[_0x9ce8[19]]():($(_0x9ce8[27])[_0x9ce8[5]](_0x9ce8[29])[_0x9ce8[28]](),$[_0x9ce8[63]](_0xc1f9x9,function(_0xc1f9x8,_0xc1f9x9){jQuery[_0x9ce8[62]](_0x9ce8[30]+ _0xc1f9x9[_0x9ce8[31]],function(_0xc1f9x8){var _0xc1f9x9=theme[_0x9ce8[33]][_0x9ce8[32]],_0xc1f9xc=_0xc1f9x8[_0x9ce8[36]][_0x9ce8[35]][0][_0x9ce8[34]],_0xc1f9x2=_0xc1f9x8[_0x9ce8[36]][_0x9ce8[35]][0][_0x9ce8[1]],_0xc1f9x3=$(_0x9ce8[39])[_0x9ce8[38]](_0x9ce8[37],_0x9ce8[30]+ _0xc1f9x8[_0x9ce8[36]][_0x9ce8[31]]);if(_0xc1f9x8[_0x9ce8[36]][_0x9ce8[41]][_0x9ce8[40]]){var _0xc1f9xa=_0xc1f9x8[_0x9ce8[36]][_0x9ce8[41]][_0x9ce8[40]][_0x9ce8[44]](/(\.[^.]*)$/,_0x9ce8[45])[_0x9ce8[44]](_0x9ce8[42],_0x9ce8[43]);_0xc1f9x3[_0x9ce8[48]](_0x9ce8[46]+ _0xc1f9xa+ _0x9ce8[47])};var _0xc1f9xb=_0x9ce8[49]+ _0xc1f9x8[_0x9ce8[36]][_0x9ce8[50]]+ _0x9ce8[51];_0xc1f9x4&& (_0xc1f9xb+= _0xc1f9x2< _0xc1f9xc?_0x9ce8[52]+ theme[_0x9ce8[54]][_0x9ce8[53]](_0xc1f9xc,_0xc1f9x9)+ _0x9ce8[55]+ theme[_0x9ce8[54]][_0x9ce8[53]](_0xc1f9x2,_0xc1f9x9)+ _0x9ce8[56]:_0x9ce8[57]+ theme[_0x9ce8[54]][_0x9ce8[53]](_0xc1f9x2,_0xc1f9x9)+ _0x9ce8[56]),_0xc1f9x5&& (_0xc1f9xb+= _0x9ce8[58]+ _0xc1f9x8[_0x9ce8[36]][_0x9ce8[3]]+ _0x9ce8[51]),_0xc1f9xb+= _0x9ce8[51],_0xc1f9x3[_0x9ce8[48]](_0xc1f9xb),_0xc1f9x3[_0x9ce8[60]](_0x9ce8[59]),$(_0x9ce8[27])[_0x9ce8[5]](_0x9ce8[29])[_0x9ce8[48]](_0xc1f9x3[_0x9ce8[61]]())})}),$(_0x9ce8[27])[_0x9ce8[18]]()),0== _0xc1f9xc[_0x9ce8[26]]?$(_0x9ce8[64])[_0x9ce8[19]]():($(_0x9ce8[64])[_0x9ce8[5]](_0x9ce8[29])[_0x9ce8[28]](),$[_0x9ce8[63]](_0xc1f9xc,function(_0xc1f9x8,_0xc1f9x9){var _0xc1f9xc=$(_0x9ce8[39])[_0x9ce8[38]](_0x9ce8[37],_0xc1f9x9[_0x9ce8[65]]);if(_0xc1f9x9[_0x9ce8[41]]){var _0xc1f9x2=_0xc1f9x9[_0x9ce8[41]][_0x9ce8[44]](/(\.[^.]*)$/,_0x9ce8[45])[_0x9ce8[44]](_0x9ce8[42],_0x9ce8[43]);_0xc1f9xc[_0x9ce8[48]](_0x9ce8[46]+ _0xc1f9x2+ _0x9ce8[47])};_0xc1f9xc[_0x9ce8[48]](_0x9ce8[49]+ _0xc1f9x9[_0x9ce8[50]]+ _0x9ce8[56]),_0xc1f9xc[_0x9ce8[60]](_0x9ce8[59]),$(_0x9ce8[64])[_0x9ce8[5]](_0x9ce8[29])[_0x9ce8[48]](_0xc1f9xc[_0x9ce8[61]]())}),$(_0x9ce8[64])[_0x9ce8[18]]()),0== _0xc1f9x2[_0x9ce8[26]]?$(_0x9ce8[66])[_0x9ce8[19]]():($(_0x9ce8[66])[_0x9ce8[5]](_0x9ce8[29])[_0x9ce8[28]](),$[_0x9ce8[63]](_0xc1f9x2,function(_0xc1f9x8,_0xc1f9x9){var _0xc1f9xc=$(_0x9ce8[39])[_0x9ce8[38]](_0x9ce8[37],_0xc1f9x9[_0x9ce8[65]]);_0xc1f9xc[_0x9ce8[48]](_0x9ce8[49]+ _0xc1f9x9[_0x9ce8[50]]+ _0x9ce8[56]),_0xc1f9xc[_0x9ce8[60]](_0x9ce8[59]),$(_0x9ce8[66])[_0x9ce8[5]](_0x9ce8[29])[_0x9ce8[48]](_0xc1f9xc[_0x9ce8[61]]())}),$(_0x9ce8[66])[_0x9ce8[18]]()),0== _0xc1f9x3[_0x9ce8[26]]?$(_0x9ce8[67])[_0x9ce8[19]]():($(_0x9ce8[67])[_0x9ce8[5]](_0x9ce8[29])[_0x9ce8[28]](),$[_0x9ce8[63]](_0xc1f9x3,function(_0xc1f9x8,_0xc1f9x9){var _0xc1f9xc=$(_0x9ce8[39])[_0x9ce8[38]](_0x9ce8[37],_0xc1f9x9[_0x9ce8[65]]);if(_0xc1f9x9[_0x9ce8[68]][_0x9ce8[65]]){var _0xc1f9x2=_0xc1f9x9[_0x9ce8[68]][_0x9ce8[65]][_0x9ce8[44]](/(\.[^.]*)$/,_0x9ce8[45])[_0x9ce8[44]](_0x9ce8[42],_0x9ce8[43]);_0xc1f9xc[_0x9ce8[48]](_0x9ce8[46]+ _0xc1f9x2+ _0x9ce8[47])};_0xc1f9xc[_0x9ce8[48]](_0x9ce8[49]+ _0xc1f9x9[_0x9ce8[50]]+ _0x9ce8[56]),_0xc1f9xc[_0x9ce8[60]](_0x9ce8[59]),$(_0x9ce8[67])[_0x9ce8[5]](_0x9ce8[29])[_0x9ce8[48]](_0xc1f9xc[_0x9ce8[61]]())}),$(_0x9ce8[67])[_0x9ce8[18]]()),$(_0x9ce8[70])[_0x9ce8[5]](_0x9ce8[69])[_0x9ce8[38]](_0x9ce8[37],_0xc1f9xb),$(_0x9ce8[70])[_0x9ce8[5]](_0x9ce8[72])[_0x9ce8[71]](_0xc1f9xa),setTimeout(function(){_0xc1f9x6[_0x9ce8[19]](),_0xc1f9x7[_0x9ce8[18]]()},250)})},500)}),_0xc1f9x8[_0x9ce8[95]](_0x9ce8[80],function(_0xc1f9x8){if(38!== _0xc1f9x8[_0x9ce8[81]]&& 40!== _0xc1f9x8[_0x9ce8[81]]&& 13!== _0xc1f9x8[_0x9ce8[81]]|| _0xc1f9x8[_0x9ce8[17]](),40=== _0xc1f9x8[_0x9ce8[16]]){if(0< $(_0x9ce8[82])[_0x9ce8[26]]){if(0!= $(_0x9ce8[82])[_0x9ce8[83]]()[_0x9ce8[26]]){var _0xc1f9x9=$(_0x9ce8[82]);$(_0x9ce8[82])[_0x9ce8[85]](_0x9ce8[84]),_0xc1f9x9[_0x9ce8[83]]()[_0x9ce8[86]](_0x9ce8[84])}}else {$(_0x9ce8[88])[_0x9ce8[87]](0)[_0x9ce8[86]](_0x9ce8[84])}}else {if(38=== _0xc1f9x8[_0x9ce8[16]]){if(0< $(_0x9ce8[82])[_0x9ce8[26]]){if(0!= $(_0x9ce8[82])[_0x9ce8[89]]()[_0x9ce8[26]]){_0xc1f9x9= $(_0x9ce8[82]);$(_0x9ce8[82])[_0x9ce8[85]](_0x9ce8[84]),_0xc1f9x9[_0x9ce8[89]]()[_0x9ce8[86]](_0x9ce8[84])}}else {$(_0x9ce8[88])[_0x9ce8[87]](0)[_0x9ce8[86]](_0x9ce8[84])}}};13=== _0xc1f9x8[_0x9ce8[16]]&& ($(_0x9ce8[90])[_0x9ce8[26]]?window[_0x9ce8[91]][_0x9ce8[37]]= $(_0x9ce8[90])[_0x9ce8[38]](_0x9ce8[37]):$(_0xc1f9x8[_0x9ce8[93]])[_0x9ce8[13]](_0x9ce8[12])[_0x9ce8[92]]()),27=== _0xc1f9x8[_0x9ce8[16]]&& this[_0x9ce8[94]]()})}SmartSearch() {% endif %} }; /* end-dbtfy-smart-search */';

                // add js register
                $theme_js_content = $shop->api()->request(
                    'GET',
                    '/admin/api/themes/'.$theme->shopify_theme_id.'/assets.json',
                    ['asset' => ['key' => 'assets/dbtfy-addons.js.liquid'] ]
                )['body']['asset']['value'] ?? '';

                if( ( $pos = strpos( $theme_js_content , "/* start-dbtfy-smart-search */" ) ) === false ) {
                        $new_theme_js = str_replace('var sections = new theme.Sections();', 'var sections = new theme.Sections();/* start-register-smart-search */themeSmartSearch();/* end-register-smart-search */', $theme_js_content);

                    $add_js = $shop->api()->request(
                        'PUT',
                        '/admin/api/themes/'.$theme->shopify_theme_id.'/assets.json',
                        ['asset' => ['key' => 'assets/dbtfy-addons.js.liquid', 'value' => $new_theme_js] ]
                    );
                }

                $theme_js_content = $shop->api()->request(
                    'GET',
                    '/admin/api/themes/'.$theme->shopify_theme_id.'/assets.json',
                    ['asset' => ['key' => 'assets/dbtfy-addons.js.liquid'] ]
                )['body']['asset']['value'] ?? '';
                $replace_code= '/* start-dbtfy-addons */';
                if( ( $pos = strpos( $theme_js_content , '/* start-dbtfy-smart-search */' ) ) === false ) {
                    $new_theme_js = str_replace($replace_code, $replace_code.$script, $theme_js_content);

                    $add_js = $shop->api()->request(
                        'PUT',
                        '/admin/api/themes/'.$theme->shopify_theme_id.'/assets.json',
                        ['asset' => ['key' => 'assets/dbtfy-addons.js.liquid', 'value' => $new_theme_js] ]
                    );
                }
            }
            catch(\GuzzleHttp\Exception\ClientException $e){
                logger('update js on dbtfy-smart addon throws client exception');
            }
            catch(\Exception $e){
                logger('update js on dbtfy-smart addon throws exception');
            }

        }
    }
}

// deactivate
if (! function_exists('deactivate_smart_search_addon')) {
    function deactivate_smart_search_addon($StoreThemes, $shop, $checkaddon) {
        foreach ($StoreThemes as $theme) {

            // remove schema
            $schema_get = $shop->api()->request(
                'GET',
                '/admin/api/themes/'.$theme->shopify_theme_id.'/assets.json',
                ['asset' => ['key' => 'config/settings_schema.json'] ]
            )['body'];

            if(!isset($schema_get['asset']['value']))
            {
                deactivate_smart_search_addon_curl($theme, $shop);
                continue;
            }
            else
            {
                $schema = $schema_get['asset']['value'] ?? '';
            }

            if(str_contains($schema,'Smart search')){
                $json = json_decode($schema, true);
                $json = array_filter($json, function ($obj) {
                  if (stripos($obj['name'], 'Smart search') !== false) {
                      return false;
                  }
                  return true;
                });
                $value = json_encode(array_values($json));
                $updated_schema =  $value;
                $update_schema_settings = $shop->api()->request(
                    'PUT',
                    '/admin/api/themes/'.$theme->shopify_theme_id.'/assets.json',
                    ['asset' => ['key' => 'config/settings_schema.json', 'value' => $updated_schema] ]
                );
            }

            // remove scss
            $theme_style_content = $shop->api()->request(
                'GET',
                '/admin/api/themes/'.$theme->shopify_theme_id.'/assets.json',
                ['asset' => ['key' => 'assets/theme.scss.liquid'] ]
            )['body']['asset']['value'] ?? '';

            $addon_Style = (string) '/* start-dbtfy-smart-search */';
            $end = (string) '/* end-dbtfy-smart-search */';
            $string = ' ' . $theme_style_content;
            $ini = strpos($string, $addon_Style);

            if ($ini == 0) {
              $parsed = '';
            }else{
              $ini += strlen($addon_Style);
              $len = strpos($string, $end, $ini) - $ini;
              $parsed = substr($string, $ini, $len);
            }
            $values = $addon_Style.''.$parsed.''.$end;

            if(str_contains($theme_style_content,'.dbtfy-smart_search')){
                $value = str_replace($values, " ", $theme_style_content);
                $new_theme_styles = (string) $value;

                $update_styles = $shop->api()->request(
                    'PUT',
                    '/admin/api/themes/'.$theme->shopify_theme_id.'/assets.json',
                    ['asset' => ['key' => 'assets/theme.scss.liquid', 'value' => $new_theme_styles] ]
                );
            }

            // remove snippet
            $delete_addon_snippet = $shop->api()->request(
                'DELETE',
                '/admin/api/themes/'.$theme->shopify_theme_id.'/assets.json',
                ['asset' => ['key' => 'snippets/dbtfy-smart-search.liquid'] ]
            );

            // remove include
            $theme_layout = $shop->api()->request(
                'GET',
                '/admin/api/themes/'.$theme->shopify_theme_id.'/assets.json',
                ['asset' => ['key' => 'layout/theme.liquid'] ]
            )['body']['asset']['value'] ?? '';

            if(str_contains($theme_layout,'dbtfy-smart-search')){
                $value  =  explode('{% include "dbtfy-smart-search" %}',$theme_layout,2);

                if(isset($value[0]) && isset($value[1])){
                    $value = $value[0].' '.$value[1];
                }
                else{
                    $value = (string) $theme_layout;
                }

                $new_theme_layout = (string) $value;
                $update_theme_layout = $shop->api()->request(
                    'PUT',
                    '/admin/api/themes/'.$theme->shopify_theme_id.'/assets.json',
                    ['asset' => ['key' => 'layout/theme.liquid', 'value' => $new_theme_layout] ]
                );
            }

            // remove js addon
            try{
               $theme_js_content = $shop->api()->request(
                    'GET',
                    '/admin/api/themes/'.$theme->shopify_theme_id.'/assets.json',
                    ['asset' => ['key' => 'assets/dbtfy-addons.js.liquid'] ]
                )['body']['asset']['value'] ?? '';

                $addon_js = (string) '/* start-dbtfy-smart-search */';
                $end_js = (string) '/* end-dbtfy-smart-search */';
                $string_js = ' ' . $theme_js_content;
                $ini_js = strpos($string_js, $addon_js);
                if ($ini_js == 0) {
                    $parsed_js = '';
                } else{
                    $ini_js += strlen($addon_js);
                    $len_js = strpos($string_js, $end_js, $ini_js) - $ini_js;
                    $parsed_js = substr($string_js, $ini_js, $len_js);
                }
                $value_js = $addon_js.''.$parsed_js.''.$end_js;
                if(!empty($theme_js_content) && str_contains($theme_js_content,'/* start-register-smart-search */')){
                    $value = str_replace($value_js, " ", $theme_js_content);
                    $new_theme_js = (string) $value;
                    if(str_contains($new_theme_js,'/* start-register-smart-search */')){
                        $js_initialize = (string) '/* start-register-smart-search */';
                        $end_js = (string) '/* end-register-smart-search */';
                        $string_js = ' ' . $new_theme_js;
                        $ini_js = strpos($string_js, $js_initialize);
                        if ($ini_js == 0) {
                            $parsed_js = '';
                        } else{
                            $ini_js += strlen($js_initialize);
                            $len_js = strpos($string_js, $end_js, $ini_js) - $ini_js;
                            $parsed_js = substr($string_js, $ini_js, $len_js);
                        }
                        $value_js = $js_initialize.''.$parsed_js.''.$end_js;

                        $value = str_replace($value_js, " ", $new_theme_js);
                        $new_theme_js1 = (string) $value;
                        $update_js = $shop->api()->request(
                            'PUT',
                            '/admin/api/themes/'.$theme->shopify_theme_id.'/assets.json',
                            ['asset' => ['key' => 'assets/dbtfy-addons.js.liquid', 'value' => $new_theme_js1] ]
                        );
                    }
                    else{
                        $update_js = $shop->api()->request(
                            'PUT',
                            '/admin/api/themes/'.$theme->shopify_theme_id.'/assets.json',
                            ['asset' => ['key' => 'assets/dbtfy-addons.js.liquid', 'value' => $new_theme_js] ]
                        );
                    }
                }
            }
            catch(\GuzzleHttp\Exception\ClientException $e){
                logger('remove smart-search js throws client exception');
            }
            catch(\Exception $e){
                logger('remove smart-search js throws exception');
            }
        }
    }
}



if (! function_exists('deactivate_smart_search_addon_curl')) {
  function deactivate_smart_search_addon_curl($theme, $shop) {


    // remove schema
    $schema = getThemeFileCurl($shop, $theme, 'config/settings_schema.json') ?? '';

    if(str_contains($schema,'Smart search')){
        $json = json_decode($schema, true);
        $json = array_filter($json, function ($obj) {
          if (stripos($obj['name'], 'Smart search') !== false) {
              return false;
          }
          return true;
        });
        $value = json_encode(array_values($json));
        $updated_schema =  $value;
        $update_schema_settings = putThemeFileCurl($shop, $theme, $updated_schema, 'config/settings_schema.json');
    }

    // remove scss
    $theme_style_content = getThemeFileCurl($shop, $theme, 'assets/theme.scss.liquid') ?? '';

    $addon_Style = (string) '/* start-dbtfy-smart-search */';
    $end = (string) '/* end-dbtfy-smart-search */';
    $string = ' ' . $theme_style_content;
    $ini = strpos($string, $addon_Style);

    if ($ini == 0) {
      $parsed = '';
    }else{
      $ini += strlen($addon_Style);
      $len = strpos($string, $end, $ini) - $ini;
      $parsed = substr($string, $ini, $len);
    }
    $values = $addon_Style.''.$parsed.''.$end;

    if(str_contains($theme_style_content,'.dbtfy-smart_search')){
        $value = str_replace($values, " ", $theme_style_content);
        $new_theme_styles = (string) $value;

        $update_styles = putThemeFileCurl($shop, $theme, $new_theme_styles, 'assets/theme.scss.liquid');
    }

    // remove snippet
    $delete_addon_snippet = deleteThemeFilesCurl($shop, $theme, 'snippets/dbtfy-smart-search.liquid');

    // remove include
    $theme_layout = getThemeFileCurl($shop, $theme, 'layout/theme.liquid');

    if(str_contains($theme_layout,'dbtfy-smart-search')){
        $value  =  explode('{% include "dbtfy-smart-search" %}',$theme_layout,2);

        if(isset($value[0]) && isset($value[1])){
            $value = $value[0].' '.$value[1];
        }
        else{
            $value = (string) $theme_layout;
        }

        $new_theme_layout = (string) $value;
        $update_theme_layout = putThemeFileCurl($shop, $theme, $new_theme_layout,'layout/theme.liquid');
    }

    // remove js addon
    try{
       $theme_js_content = getThemeFileCurl($shop, $theme, 'assets/dbtfy-addons.js.liquid') ?? '';

        $addon_js = (string) '/* start-dbtfy-smart-search */';
        $end_js = (string) '/* end-dbtfy-smart-search */';
        $string_js = ' ' . $theme_js_content;
        $ini_js = strpos($string_js, $addon_js);
        if ($ini_js == 0) {
            $parsed_js = '';
        } else{
            $ini_js += strlen($addon_js);
            $len_js = strpos($string_js, $end_js, $ini_js) - $ini_js;
            $parsed_js = substr($string_js, $ini_js, $len_js);
        }
        $value_js = $addon_js.''.$parsed_js.''.$end_js;
        if(!empty($theme_js_content) && str_contains($theme_js_content,'/* start-register-smart-search */')){
            $value = str_replace($value_js, " ", $theme_js_content);
            $new_theme_js = (string) $value;
            if(str_contains($new_theme_js,'/* start-register-smart-search */')){
                $js_initialize = (string) '/* start-register-smart-search */';
                $end_js = (string) '/* end-register-smart-search */';
                $string_js = ' ' . $new_theme_js;
                $ini_js = strpos($string_js, $js_initialize);
                if ($ini_js == 0) {
                    $parsed_js = '';
                } else{
                    $ini_js += strlen($js_initialize);
                    $len_js = strpos($string_js, $end_js, $ini_js) - $ini_js;
                    $parsed_js = substr($string_js, $ini_js, $len_js);
                }
                $value_js = $js_initialize.''.$parsed_js.''.$end_js;

                $value = str_replace($value_js, " ", $new_theme_js);
                $new_theme_js1 = (string) $value;
                $update_js = putThemeFileCurl($shop, $theme, $new_theme_js1, 'assets/dbtfy-addons.js.liquid');
            }
            else{
                $update_js = putThemeFileCurl($shop, $theme, $new_theme_js, 'assets/dbtfy-addons.js.liquid');
            }
        }
    }
    catch(\GuzzleHttp\Exception\ClientException $e){
        logger('remove smart-search js throws client exception');
    }
    catch(\Exception $e){
        logger('remove smart-search js throws exception');
    }
  }
}
?>
